In [1]:
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# %                   SCF-TB - PROXY APPLICATION                      %
# %                   A.M.N. Niklasson, M. Kulichenko. T1, LANL       %
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# % Total Energy Function:                                            %
# % E = 2Tr[H0(D-D0)] + (1/2)*sum_i U_i q_i^2 +                       %
# %      + (1/2)sum_{i,j (i!=j)} q_i C_{ij} q_j - Efield*dipole       %
# % dipole = sum_i R_{i} q_i                                          %
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

import torch
import warnings
import logging
import os
# to disable torchdynamo completely. Faster for smaller systems and single-point calculations.
os.environ["TORCHDYNAMO_DISABLE"] = "1"  # hard-disable capture

import numpy as np
import matplotlib.pyplot as plt

from dftorch.SCF import SCFx, SCFx_batch, scf_x_os
from dftorch.Spin import get_spin_energy, get_h_spin
from dftorch.Energy import Energy

from dftorch.Forces import Forces, forces_spin

from dftorch.Constants import Constants
from dftorch.Structure import Structure, StructureBatch
from dftorch.MD import MDXL, MDXLBatch
from dftorch.ESDriver import ESDriver, ESDriverBatch

### Configure torch and torch.compile ###
# Silence warnings and module logs
warnings.filterwarnings("ignore")
os.environ["TORCH_LOGS"] = ""               # disable PT2 logging
os.environ["TORCHINDUCTOR_VERBOSE"] = "0"
os.environ["TORCHDYNAMO_VERBOSE"] = "0"
logging.getLogger("torch.fx").setLevel(logging.CRITICAL)
logging.getLogger("torch.fx.experimental.symbolic_shapes").setLevel(logging.CRITICAL)
logging.getLogger("torch.fx.experimental.recording").setLevel(logging.CRITICAL)
# Enable dynamic shape capture for dynamo
torch._dynamo.config.capture_dynamic_output_shape_ops = True
# default data type
torch.set_default_dtype(torch.float64)

torch.cuda.empty_cache()

# MD with PBC and PME
### Note, PME does not work properly for small cells (< 20x20x20)
### Also, do not use PME without PBC.

## First, SCF and forces

In [2]:
%%time
dftorch_params = {
    'coul_method': 'PME', # 'FULL' for full coulomb matrix, 'PME' for PME method
    'Coulomb_acc': 5e-5,   # Coulomb accuracy for full coulomb calcs or t_err for PME
    'cutoff': 12.0,        # Coulomb cutoff
    'PME_order': 4,        # Ignored for FULL coulomb method

    'SCF_MAX_ITER': 100,    # Maximum number of SCF iterations
    'SCF_TOL': 1e-6,       # SCF convergence tolerance on density matrix
    'SCF_ALPHA': 0.04,      # Scaled delta function coefficient. Acts as linear mixing coefficient used before Krylov acceleration starts.

    'KRYLOV_MAXRANK': 30,  # Maximum Krylov subspace rank
    'KRYLOV_TOL': 1e-5,    # Krylov subspace convergence tolerance in SCF
    'KRYLOV_TOL_MD': 1e-4, # Krylov subspace convergence tolerance in MD SCF
    'KRYLOV_START': 50,     # Number of initial SCF iterations before starting Krylov acceleration
                }
                
# Initial data, load atoms and coordinates, etc in COORD.dat
device = 'cuda' if torch.cuda.is_available() else 'cpu'
#filename = '8RNT.xyz'      
filename = 'COORD.xyz'            # Solvated acetylacetone and glycine molecules in H20, Na, Cl
LBox = torch.tensor([45.0, 45.0, 40.0], device=device) # Simulation box size in Angstroms. Only cubic boxes supported for now.
# Create constants container. Set path to SKF files.
const = Constants(filename,
                  #'/home/maxim/Projects/DFTB/DFTorch/tests/sk_orig/ptbp/complete_set',
                  'C:\\000_MyFiles\\Programs\\DFTorch\\tests\\sk_orig\\ptbp\\complete_set\\',
                  magnetic_hubbard_ldep=False
                  ).to(device)

# Create structure object. Define total charge and electronic temperature.
structure1 = Structure(filename, LBox, const, charge=7, Te=500.0, device=device)

# Create ESDriver object and run SCF calculation
# electronic_rcut and repulsive_rcut are in Angstroms.
# They should be >= cutoffs defined in SKF files for the element pair with largest cutoff present in the system.
es_driver = ESDriver(dftorch_params, electronic_rcut=8.0, repulsive_rcut=6.0, device=device)
es_driver(structure1, const, do_scf=True)
es_driver.calc_forces(structure1, const) # Calculate forces after SCF

int64
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\ptbp\complete_set\H-H.skf
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\ptbp\complete_set\H-C.skf
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\ptbp\complete_set\C-H.skf
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\ptbp\complete_set\C-C.skf
### Do SCF ###
  Initial DM_Fermi

Starting cycle
Iter 1
Res = 4.970438028, dEc = 168.921345355, t = 0.3 s

Iter 2
Res = 4.600868459, dEc = 3.820100542, t = 0.1 s

Iter 3
Res = 4.253910080, dEc = 3.337667615, t = 0.1 s

Iter 4
Res = 3.924703779, dEc = 2.920118794, t = 0.1 s

Iter 5
Res = 3.610067822, dEc = 2.556168261, t = 0.1 s

Iter 6
Res = 3.307865716, dEc = 2.238126024, t = 0.0 s

Iter 7
Res = 3.016962430, dEc = 1.960234594, t = 0.0 s

Iter 8
Res = 2.737416648, dEc = 1.717850650, t = 0.0 s

Iter 9
Res = 2.470613421, dEc = 1.506998633, t = 0.0 s

Iter 10
Res = 2.219054127, dEc = 1.324142228, t = 0.0 s

Iter 11
Res = 1.985715603, dEc = 1.166092188, t = 0.0 s

Iter 12
Res = 1.773235023, dEc = 1.0

In [3]:
#charges:
structure1.q

tensor([-0.2438, -0.7706, -0.4516, -0.3950, -0.7243,  0.2517, -0.4235, -0.4312,
        -0.3921, -0.4288,  0.2427, -0.3826, -0.4541, -0.4357, -0.4114, -0.2073,
        -0.3938, -0.7813, -0.7546, -0.4127])

In [4]:
#MO coeffs
structure1.Q

tensor([[ 1.7793e-01, -3.5631e-01,  4.9032e-01,  ..., -2.9076e-01,
          3.5272e-01, -2.0136e-01],
        [-6.8824e-02,  8.9261e-02, -1.3560e-02,  ..., -1.9987e-01,
          8.2232e-02,  1.5840e-02],
        [-2.2904e-04,  1.4454e-03, -2.4637e-04,  ..., -8.8955e-02,
         -2.0499e-02,  5.5811e-02],
        ...,
        [-3.3998e-02, -8.0351e-02, -1.3895e-01,  ..., -1.3726e-01,
         -1.1252e-01, -6.3736e-02],
        [-3.9725e-02, -9.2969e-02, -1.5810e-01,  ..., -2.6449e-01,
         -2.3171e-01, -1.4924e-01],
        [-1.4647e-01, -2.3625e-01, -2.1485e-01,  ..., -2.5871e-01,
         -3.5329e-01, -3.0009e-01]])

In [5]:
print("Total Energy: ", structure1.e_tot)
print("Chemical Potential: ", structure1.mu0)

Total Energy:  tensor(-138.3300)
Chemical Potential:  tensor(-44.0957)


## MD

In [6]:
torch.manual_seed(0)
temperature_K = torch.tensor(1.0, device=structure1.device)
mdDriver = MDXL(es_driver, const, temperature_K=temperature_K)
# Set number of steps, time step (fs), dump interval and trajectory filename
mdDriver.run(structure1, dftorch_params, num_steps=20, dt=0.3, dump_interval=5, traj_filename='md_trj.xyz')

########## Step = 0 ##########
H0: 0.019 s
H1: 0.081 s
  rank: 0, Fel = 0.000164
  rank: 1, Fel = 0.000130
  rank: 2, Fel = 0.000019
KER: 0.183 s
F AND E: 0.001 s
ETOT = -138.32770692, EPOT = -138.54762254, EKIN = 0.00232668, T = 0.89999886, ResErr = 0.000000, t = 0.3 s
0.0 GB


########## Step = 1 ##########
H0: 0.018 s
H1: 0.008 s
  rank: 0, Fel = 0.000355
  rank: 1, Fel = 0.000250
  rank: 2, Fel = 0.000024
KER: 0.018 s
F AND E: 0.001 s
ETOT = -138.32879379, EPOT = -139.16758910, EKIN = 0.21882875, T = 84.64663830, ResErr = 0.001296, t = 0.0 s
0.0 GB


########## Step = 2 ##########
H0: 0.018 s
H1: 0.012 s
  rank: 0, Fel = 0.000228
  rank: 1, Fel = 0.000190
  rank: 2, Fel = 0.000013
KER: 0.189 s
F AND E: 0.001 s
ETOT = -138.33023131, EPOT = -140.13703110, EKIN = 0.83735779, T = 323.90406995, ResErr = 0.002632, t = 0.2 s
0.0 GB


########## Step = 3 ##########
H0: 0.020 s
H1: 0.070 s
  rank: 0, Fel = 0.000032
KER: 0.005 s
F AND E: 0.001 s
ETOT = -138.33158250, EPOT = -141.38006778, EK

# MD without PBC and with full Coulomb
### Do not use PME without PBC.
### Turn on PBC if necessary

## First, SCF and forces

In [7]:
%%time
dftorch_params = {
    'coul_method': 'FULL', # 'FULL' for full coulomb matrix, 'PME' for PME method
    'Coulomb_acc': 5e-5,   # Coulomb accuracy for full coulomb calcs or t_err for PME
    'cutoff': 12.0,        # Coulomb cutoff
    'PME_order': 4,        # Ignored for FULL coulomb method

    'SCF_MAX_ITER': 100,    # Maximum number of SCF iterations
    'SCF_TOL': 1e-6,       # SCF convergence tolerance on density matrix
    'SCF_ALPHA': 0.05,      # Scaled delta function coefficient. Acts as linear mixing coefficient used before Krylov acceleration starts.

    'KRYLOV_MAXRANK': 30,  # Maximum Krylov subspace rank
    'KRYLOV_TOL': 1e-5,    # Krylov subspace convergence tolerance in SCF
    'KRYLOV_TOL_MD': 1e-4, # Krylov subspace convergence tolerance in MD SCF
    'KRYLOV_START': 50,     # Number of initial SCF iterations before starting Krylov acceleration
                }
                
# Initial data, load atoms and coordinates, etc in COORD.dat
device = 'cuda' if torch.cuda.is_available() else 'cpu'
#filename = '8RNT.xyz'      
filename = 'COORD.xyz'            # Solvated acetylacetone and glycine molecules in H20, Na, Cl
#LBox = torch.tensor([45.0, 45.0, 40.0], device=device) # Simulation box size in Angstroms. Only cubic boxes supported for now.
LBox = None
# Create constants container. Set path to SKF files.
const = Constants(filename,
                  #'/home/maxim/Projects/DFTB/DFTorch/tests/sk_orig/ptbp/complete_set',
                  'C:\\000_MyFiles\\Programs\\DFTorch\\tests\\sk_orig\\ptbp\\complete_set\\',
                  magnetic_hubbard_ldep=False
                  ).to(device)

# Create structure object. Define total charge and electronic temperature.
structure1 = Structure(filename, LBox, const, charge=7, Te=500.0, device=device)

# Create ESDriver object and run SCF calculation
# electronic_rcut and repulsive_rcut are in Angstroms.
# They should be >= cutoffs defined in SKF files for the element pair with largest cutoff present in the system.
es_driver = ESDriver(dftorch_params, electronic_rcut=8.0, repulsive_rcut=6.0, device=device)
es_driver(structure1, const, do_scf=True)
es_driver.calc_forces(structure1, const) # Calculate forces after SCF

int64
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\ptbp\complete_set\H-H.skf
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\ptbp\complete_set\H-C.skf
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\ptbp\complete_set\C-H.skf
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\ptbp\complete_set\C-C.skf
CoulombMatrix_vectorized
  Coulomb_Real t 0.0 s
  Coulomb_k t 0.0 s

### Do SCF ###
  Initial DM_Fermi

Starting cycle
Iter 1
Res = 5.363231945, dEc = 87.673319089, t = 0.0 s

Iter 2
Res = 4.657356940, dEc = 3.964600651, t = 0.0 s

Iter 3
Res = 3.986181824, dEc = 3.021792355, t = 0.0 s

Iter 4
Res = 3.350619078, dEc = 2.284765686, t = 0.0 s

Iter 5
Res = 2.760847345, dEc = 1.723482967, t = 0.0 s

Iter 6
Res = 2.237277013, dEc = 1.310032985, t = 0.0 s

Iter 7
Res = 1.798117539, dEc = 1.012956841, t = 0.0 s

Iter 8
Res = 1.451655050, dEc = 0.800232326, t = 0.0 s

Iter 9
Res = 1.201693635, dEc = 0.645979078, t = 0.0 s

Iter 10
Res = 1.040285109, dEc = 0.532373532, t = 0.0 s

Iter 11
Res = 0.935851488

In [8]:
torch.manual_seed(0)
temperature_K = torch.tensor(1.0, device=structure1.device)
mdDriver = MDXL(es_driver, const, temperature_K=temperature_K)
# Set number of steps, time step (fs), dump interval and trajectory filename
mdDriver.run(structure1, dftorch_params, num_steps=20, dt=0.3, dump_interval=5, traj_filename='md_trj.xyz')

########## Step = 0 ##########
CoulombMatrix_vectorized
  Coulomb_Real t 0.0 s
  Coulomb_k t 0.0 s

H0: 0.036 s
H1: 0.001 s
  rank: 0, Fel = 0.000163
  rank: 1, Fel = 0.000087
KER: 0.001 s
F AND E: 0.002 s
ETOT = -207.33150334, EPOT = -207.47284758, EKIN = 0.00232668, T = 0.89999886, ResErr = 0.000000, t = 0.1 s
0.0 GB


########## Step = 1 ##########
CoulombMatrix_vectorized
  Coulomb_Real t 0.0 s
  Coulomb_k t 0.0 s

H0: 0.019 s
H1: 0.001 s
  rank: 0, Fel = 0.000382
  rank: 1, Fel = 0.000137
  rank: 2, Fel = 0.000045
KER: 0.001 s
F AND E: 0.002 s
ETOT = -207.33232463, EPOT = -207.86291058, EKIN = 0.14052295, T = 54.35663959, ResErr = 0.001302, t = 0.0 s
0.0 GB


########## Step = 2 ##########
CoulombMatrix_vectorized
  Coulomb_Real t 0.0 s
  Coulomb_k t 0.0 s

H0: 0.021 s
H1: 0.001 s
  rank: 0, Fel = 0.000259
  rank: 1, Fel = 0.000183
  rank: 2, Fel = 0.000028
KER: 0.001 s
F AND E: 0.001 s
ETOT = -207.33361092, EPOT = -208.47123406, EKIN = 0.52929966, T = 204.74200725, ResErr = 0.002

# Open-Shell single point. No MD for open-shells for now.
### PBC ok. PME not ok.
### Turn on PBC if necessary

## First, SCF and forces

In [9]:
%%time
dftorch_params = {
    'UNRESTRICTED': True,
    'coul_method': 'FULL', # 'FULL' for full coulomb matrix, 'PME' for PME method
    'Coulomb_acc': 5e-5,   # Coulomb accuracy for full coulomb calcs or t_err for PME
    'cutoff': 12.0,        # Coulomb cutoff
    'PME_order': 4,        # Ignored for FULL coulomb method

    'SCF_MAX_ITER': 100,    # Maximum number of SCF iterations
    'SCF_TOL': 1e-6,       # SCF convergence tolerance on density matrix
    'SCF_ALPHA': 0.05,      # Scaled delta function coefficient. Acts as linear mixing coefficient used before Krylov acceleration starts.

    'KRYLOV_MAXRANK': 30,  # Maximum Krylov subspace rank
    'KRYLOV_TOL': 1e-6,    # Krylov subspace convergence tolerance in SCF
    'KRYLOV_TOL_MD': 1e-4, # Krylov subspace convergence tolerance in MD SCF
    'KRYLOV_START': 50,     # Number of initial SCF iterations before starting Krylov acceleration
                }
                
# Initial data, load atoms and coordinates, etc in COORD.dat
device = 'cuda' if torch.cuda.is_available() else 'cpu'
#filename = '8RNT.xyz'      
filename = 'COORD.xyz'            # Solvated acetylacetone and glycine molecules in H20, Na, Cl
#LBox = torch.tensor([45.0, 45.0, 40.0], device=device) # Simulation box size in Angstroms. Only cubic boxes supported for now.
LBox = None
# Create constants container. Set path to SKF files.
const = Constants(filename,
                  #'/home/maxim/Projects/DFTB/DFTorch/tests/sk_orig/ptbp/complete_set',
                  #'C:\\000_MyFiles\\Programs\\DFTorch\\tests\\sk_orig\\ptbp\\complete_set\\',
                    'C:\\000_MyFiles\\Programs\\DFTorch\\tests\\sk_orig\\mio-1-1\\mio-1-1\\',
                    magnetic_hubbard_ldep=False
                  ).to(device)

# Create structure object. Define total charge and electronic temperature.
structure1 = Structure(filename, LBox, const, charge=7, Te=100.0, device=device)

# Create ESDriver object and run SCF calculation
# electronic_rcut and repulsive_rcut are in Angstroms.
# They should be >= cutoffs defined in SKF files for the element pair with largest cutoff present in the system.
es_driver = ESDriver(dftorch_params, electronic_rcut=8.0, repulsive_rcut=6.0, device=device)
es_driver(structure1, const, do_scf=True)
es_driver.calc_forces(structure1, const) # Calculate forces after SCF

int64
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\mio-1-1\mio-1-1\H-H.skf
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\mio-1-1\mio-1-1\H-C.skf
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\mio-1-1\mio-1-1\C-H.skf
C:\000_MyFiles\Programs\DFTorch\tests\sk_orig\mio-1-1\mio-1-1\C-C.skf
torch.float64 torch.int64
CoulombMatrix_vectorized
  Coulomb_Real t 0.0 s
  Coulomb_k t 0.0 s

### Do SCF ###
  Initial DM_Fermi
tensor(-8.1936) tensor([-8.1936, -8.1936])
tensor([-0.7075,  0.3191, -0.2453, -0.4050, -0.3318, -0.1537, -0.6987, -0.2105,
        -0.3484, -0.4840, -0.4302, -0.4960, -0.7002, -0.1962, -0.3061, -0.4868,
        -0.4483, -0.5056, -0.7045,  0.3545, -0.1923, -0.2198, -0.2645, -0.4580]) tensor(-8.3200)

Starting cycle
Iter 1
Res = 2.827265197, dEc = 90.003790309, t = 0.0 s

Iter 2
Res = 2.488659623, dEc = 3.112643023, t = 0.0 s

Iter 3
Res = 2.171777101, dEc = 2.466058098, t = 0.0 s

Iter 4
Res = 1.871681299, dEc = 1.948145140, t = 0.0 s

Iter 5
Res = 1.587503137, dEc = 1.538312447,

In [10]:
# atomic charges
structure1.q_tot_atom

tensor([-0.4615, -0.6048, -0.3799, -0.3323, -0.5340, -0.2611, -0.3652, -0.3621,
        -0.3297, -0.3652, -0.2633, -0.3206, -0.3878, -0.3772, -0.3489, -0.4418,
        -0.3142, -0.5983, -0.5934, -0.3587])

In [11]:
# atomic charges: alpha and beta channels
structure1.q_spin_atom

tensor([[-0.2308, -0.3024, -0.1900, -0.1661, -0.2670, -0.1305, -0.1826, -0.1810,
         -0.1648, -0.1826, -0.1317, -0.1603, -0.1939, -0.1886, -0.1744, -0.2209,
         -0.1571, -0.2992, -0.2967, -0.1793],
        [-0.2308, -0.3024, -0.1900, -0.1661, -0.2670, -0.1305, -0.1826, -0.1810,
         -0.1648, -0.1826, -0.1317, -0.1603, -0.1939, -0.1886, -0.1744, -0.2209,
         -0.1571, -0.2992, -0.2967, -0.1793]])

In [12]:
# charges per shell(s,p,d): alpha and beta channels
structure1.q_spin_sr

tensor([[-0.3024,  0.0717, -0.3024, -0.1900, -0.1661, -0.2670, -0.3097,  0.1791,
         -0.1826, -0.1810, -0.1648, -0.1826, -0.3091,  0.1775, -0.1603, -0.1939,
         -0.1886, -0.1744, -0.3028,  0.0819, -0.1571, -0.2992, -0.2967, -0.1793],
        [-0.3024,  0.0717, -0.3024, -0.1900, -0.1661, -0.2670, -0.3097,  0.1791,
         -0.1826, -0.1810, -0.1648, -0.1826, -0.3091,  0.1775, -0.1603, -0.1939,
         -0.1886, -0.1744, -0.3028,  0.0819, -0.1571, -0.2992, -0.2967, -0.1793]])

In [13]:
# net spin per shell
structure1.net_spin_sr

tensor([-5.2655e-07, -1.7531e-05, -3.0066e-06, -8.1712e-07,  4.6461e-09,
        -5.0376e-06,  1.2975e-07,  1.6360e-06,  1.5702e-06, -8.6197e-07,
        -1.3296e-07,  8.5943e-07,  7.8992e-07,  3.8630e-06,  4.1112e-07,
        -1.1727e-06, -1.6417e-06,  1.2966e-06,  5.5267e-07,  1.3664e-05,
        -3.2837e-07,  4.2101e-06,  8.7550e-07,  1.1930e-06])

In [14]:
# net spin (sums to a number of unpolarized electrons)
structure1.net_spin_sr.sum()

tensor(1.2212e-15)

In [15]:
#forces
structure1.f_tot

tensor([[ 2.7802, -3.0125, -1.2317, -0.6343, -4.8237, -0.2992, -0.2916, -1.2318,
         -0.4715, -2.8980,  2.2681,  0.7615,  0.9627,  1.2665, -0.0477, -0.2328,
          1.2266,  2.8757,  3.7416, -0.7081],
        [ 0.9940, -2.2218,  2.0855, -2.7342,  2.0584, -0.2182, -1.8516,  1.5912,
         -2.2882,  2.4383, -0.3065, -1.3437,  1.9918, -2.9698,  2.3653,  0.1059,
         -1.5215,  2.0455, -2.7814,  2.5609],
        [ 0.9996, -4.0428, -1.6572,  1.3315,  3.0067, -1.7030, -2.8337, -1.3807,
          1.1417,  4.1439, -2.0414, -1.9833, -1.5056,  1.7852,  3.9345, -3.6748,
         -2.0731, -0.7259,  2.8064,  4.4719]])