In [1]:
import torch
import warnings
import logging
import os

# to disable torchdynamo completely. Faster for smaller systems and single-point calculations.
os.environ["TORCHDYNAMO_DISABLE"] = "1"  # hard-disable capture

from dftorch import (
    Constants,
    Structure,
    StructureBatch,
    MDXL,
    MDXLBatch,
    MDXLOS,
    ESDriver,
    ESDriverBatch,
)

### Configure torch and torch.compile ###
# Silence warnings and module logs
warnings.filterwarnings("ignore")
os.environ["TORCH_LOGS"] = ""  # disable PT2 logging
os.environ["TORCHINDUCTOR_VERBOSE"] = "0"
os.environ["TORCHDYNAMO_VERBOSE"] = "0"
logging.getLogger("torch.fx").setLevel(logging.CRITICAL)
logging.getLogger("torch.fx.experimental.symbolic_shapes").setLevel(logging.CRITICAL)
logging.getLogger("torch.fx.experimental.recording").setLevel(logging.CRITICAL)
# Enable dynamic shape capture for dynamo
torch._dynamo.config.capture_dynamic_output_shape_ops = True
# default data type
torch.set_default_dtype(torch.float64)

torch.cuda.empty_cache()

# 0. NVIDIA Alchemi for neighbor list construction
### Uncomment code below to use NVIDIA Alchemi for neighbor list construction.

In [2]:
# import dftorch._nearestneighborlist as _nnl
# _nnl.USE_ALCHEMI = True   # all subsequent calls use alchemi by default

# 1. MD with PBC and PME
### Note, cell dimensions must be >= (2 x COULOMB_CUTOFF) if using PME.

## First, SCF and forces

In [ ]:
%%time
dftorch_params = {
    ### mandatory: ###
    "FILENAME": "COORD.xyz",
    "CELL": [[25.0, 0.0, 0.0], [0.0, 25.0, 0.0], [0.0, 0.0, 25.0]],  # Simulation box vectors in Angstroms. Can be read from .pdb file.
    "SKFPATH": "sk_orig/mio-1-1/mio-1-1/",  # Path to SKF files
    "T_ELECTRONIC": 1000.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "COUL_METHOD": "PME",  # 'FULL' for full coulomb matrix, 'PME' for Particle Mesh Ewald method

    ### optional with default values: ###
    # "SCF_ALPHA": 0.1,  # Scaled delta function coefficient. Acts as linear mixing coefficient used before Krylov acceleration starts.
    # "SCF_MAX_ITER": 100,  # Maximum number of SCF iterations. Default is 100.
    # "SCF_TOL": 1e-6,  # SCF convergence tolerance on density matrix
    
    # "COULOMB_CUTOFF": 10.0,  # Coulomb cutoff
    # "COULOMB_ACC": 1e-5,  # Coulomb accuracy for full coulomb calcs or t_err for PME
    # "PME_ORDER": 4,  # Ignored for FULL coulomb method

    # "KRYLOV_START": 10,  # Number of initial SCF iterations before starting Krylov acceleration
    # "KRYLOV_MAXRANK": 20,  # Maximum Krylov subspace rank
    # "KRYLOV_TOL": 1e-6,  # Krylov subspace convergence tolerance in SCF
    # "KRYLOV_TOL_MD": 1e-2,  # Krylov subspace convergence tolerance in MD SCF

    # "CHARGE": 0,  # Total charge of the system. Default is 0 (neutral).
    # "UNRESTRICTED": False, # Whether to perform unrestricted (spin-polarized) calculation. Default is False (restricted).
    # "SPIN_POL": 0,  # Spin polarization (N_alpha - N_beta). Default is 0 (non-magnetic).
    # "SHARED_MU": False, # Whether to use shared chemical potential for alpha and beta spin channels. Default is False (per-channel chemical potentials).
    # "BROKEN_SYM": False, # if True, mix 10 % of lumo in homo at initialization.
    # "MAGNETIC_HUBBARD_LDEP": False,  # Whether to use magnetic Hubbard LDEP. Default is False.

    # "ELECTRIC_FIELD": [0.0, 0.0, 0.0],  # External electric field in V/Angstrom. Default is None

    # "D3_PARAMS": {"s6": 1.0, "s8": 0.5883, "a1": 0.5719, "a2": 3.6107}, # D3 dispersion parameters
    
    # "SOLVENT_PARAM_FILE": "sk_orig/mio-1-1/mio-1-1/solvation/param_gbsa1_h2o.txt",
    # "SOLVATION_MODEL": "gbsa", # gbsa (default) or alpb
    # "GBSA_DIFFERENTIABLE": True,  # Whether to use differentiable GBSA. Default is False.

    # "H_DAMP_EXP": 4.0,  # Exponential damping factor for hydrogen bonds. Default is None.
    # "H5_PARAMS": {
    #     "r_scaling": 0.714,
    #     "w_scaling": 0.25,
    #     "h5_scaling": {8: 0.06, 7: 0.18, 16: 0.21},  # O, N, S
    # }, # H5 correction. Default is None. Mutually exclusive with H_DAMP_EXP.
    # 'ANDERSON_DEPTH': 0 # Anderson extrapolation depth for MD SCF. Default is 8. Set to 0 to disable Anderson extrapolation and use simple linear mixing in MD SCF.

    # "GRAD_PARAM": False,  # Whether to use parameter gradients. Default is False.
    # "GRAD_XYZ": False,  # Whether to use gradients with respect to atomic coordinates. Default is False.
    # "GRAD_CELL": False,  # Whether to use gradients with respect to cell parameters. Default is False.
}

device = "cuda" if torch.cuda.is_available() else "cpu"

# Constants container.
const = Constants(dftorch_params).to(device)

# Structure object.
structure1 = Structure(dftorch_params, const, device=device)

# Electronic structuredriver and SCF calculation
es_driver = ESDriver(dftorch_params, device=device)
es_driver(structure1, const, do_scf=True)
es_driver.calc_forces(structure1, const)  # Calculate forces after SCF
es_driver.calc_stress(structure1, const)  # Calculate stress after SCF

DFTB3: False
### Do _scf ###
  Initial dm_fermi
  Initial mu = 0.1306

Starting cycle
Iter 1
Res = 0.174511164, dEc = 0.052526687, t = 1.2 s

Iter 2
Res = 0.133178871, dEc = 0.763474671, t = 0.0 s

Iter 3
Res = 0.012217255, dEc = 0.998521804, t = 0.0 s

Iter 4
Res = 0.000376813, dEc = 0.043420001, t = 0.0 s

Iter 5
Res = 0.000201801, dEc = 0.003305471, t = 0.0 s

Iter 6
Res = 0.000039566, dEc = 0.001254883, t = 0.0 s

Iter 7
Res = 0.000001801, dEc = 0.000139735, t = 0.0 s

Iter 8
Res = 0.000001074, dEc = 0.000001244, t = 0.0 s

Iter 9
Res = 0.000000169, dEc = 0.000004427, t = 0.0 s

CPU times: user 5.44 s, sys: 628 ms, total: 6.07 s
Wall time: 2.53 s


In [4]:
Ha = 0.0367493  # correct eV → Ha conversion
# print(f"  {'net spin':22s} {structure1.net_spin_sr.sum().item():12.4f}")
print(
    f"  {'Chemical Potential':22s} {structure1.mu0 * Ha:12.6f} Ha  ({structure1.mu0:12.6f} Ev)"
)
print(f"{'Energy Components':─^52}")
print(
    f"  {'E_total':22s} {structure1.e_tot * Ha:12.6f} Ha  ({structure1.e_tot:12.6f} Ev)"
)
print(
    f"  {'E_band':22s} {structure1.e_band0 * Ha:12.6f} Ha  ({structure1.e_band0:12.6f} Ev)"
)
print(
    f"  {'E_coulomb':22s} {structure1.e_coul * Ha:12.6f} Ha  ({structure1.e_coul:12.6f} Ev)"
)
print(
    f"  {'E_repulsion':22s} {structure1.e_repulsion * Ha:12.6f} Ha  ({structure1.e_repulsion:12.6f} Ev)"
)
print(
    f"  {'E_entropy (-TS)':22s} {structure1.e_entropy * Ha:12.6f} Ha  ({structure1.e_entropy:12.6f} Ev)"
)
# print(f"  {'E_spin':22s} {structure1.e_spin.item()*Ha:12.6f} Ha  ({structure1.e_spin.item():12.6f} eV)")
print(f"{'─' * 52}")
print(
    f"  {'E_free (F=E-TS)':22s} {(structure1.e_tot - structure1.e_entropy) * Ha:12.6f} Ha"
)

  Chemical Potential         0.013372 Ha  (    0.363872 Ev)
─────────────────Energy Components──────────────────
  E_total                   -2.807069 Ha  (  -76.384296 Ev)
  E_band                    -2.806049 Ha  (  -76.356527 Ev)
  E_coulomb                  0.008233 Ha  (    0.224033 Ev)
  E_repulsion               -0.009254 Ha  (   -0.251802 Ev)
  E_entropy (-TS)            0.000000 Ha  (    0.000000 Ev)
────────────────────────────────────────────────────
  E_free (F=E-TS)           -2.807069 Ha


In [5]:
# total forces
structure1.f_tot

tensor([[-7.3038, -0.4120, -5.5981, -2.6596, -1.3459,  0.8168,  0.9404, -5.0542,
         -1.9465,  5.3640,  0.5464,  1.0173, -5.1237, -1.8800,  5.2904, 10.0701,
          1.6909, -0.8837,  0.6773,  5.7940],
        [ 0.2057, -0.1111, -0.6874, -0.4509,  0.8452,  0.6972, -0.1738, -0.6375,
         -0.9824,  1.0365,  0.7354, -0.2126, -0.7517, -0.8772,  1.1052,  0.4230,
          0.0638, -0.9181, -0.4811,  1.1719],
        [-2.0593, -0.1140, -0.4980, -0.8283,  0.6982,  0.2309,  0.0278, -0.8519,
         -0.9190,  1.4814,  0.1443, -0.0216, -0.7520, -0.9496,  1.5775,  1.0394,
          0.1708,  0.3830, -0.2174,  1.4577]], device='cuda:0')

In [6]:
# total stresses
structure1.stress_tot

tensor([[-0.0046,  0.0003, -0.0006],
        [ 0.0003, -0.0007, -0.0001],
        [-0.0006, -0.0001, -0.0008]], device='cuda:0')

In [7]:
# charges:
structure1.q

tensor([ 0.4848, -0.1008, -0.1642, -0.1252, -0.0984,  0.6170, -0.1163, -0.1613,
        -0.1223, -0.2187,  0.6144, -0.1181, -0.1620, -0.1208, -0.2180,  0.5056,
        -0.1133, -0.0794, -0.0835, -0.2193], device='cuda:0')

In [8]:
# MO coeffs
structure1.Q

tensor([[ 0.2888, -0.4240,  0.4409,  ..., -0.2147,  0.1975, -0.1110],
        [ 0.0683, -0.0498, -0.0511,  ..., -0.0042,  0.0565, -0.0565],
        [-0.0008,  0.0011, -0.0032,  ..., -0.0147,  0.0663, -0.0566],
        ...,
        [ 0.0608,  0.1374,  0.1938,  ...,  0.1116,  0.0842,  0.0377],
        [ 0.0672,  0.1501,  0.2073,  ...,  0.2069,  0.1590,  0.0782],
        [ 0.1518,  0.2448,  0.1753,  ...,  0.3422,  0.4165,  0.2993]],
       device='cuda:0')

## MD

In [9]:
torch.manual_seed(0)
temperature_K = torch.tensor(1.0, device=structure1.device)
mdDriver = MDXL(es_driver, const, temperature_K=temperature_K)

mdDriver.enable_langevin(gamma=0.02)  # thermostat. also needed for proper NPT
mdDriver.enable_barostat(  # barostat
    target_pressure=0.0,  # GPa
    tau=200.0,  # fs
    isotropic=True,
    compressibility=4.57e-5,  # 1/bar (water at 300 K)
)

# Set number of steps, time step (fs), dump interval and trajectory filename
mdDriver.run(
    structure1,
    dftorch_params,
    num_steps=5,
    dt=0.3,
    dump_interval=5,
    traj_filename="md_trj.xyz",
)

########## Step = 0 ##########
H0: 0.091 s
H1: 0.023 s
  rank: 0, Fel = 0.000468
KER: 0.012 s
F AND E: 0.145 s
ETOT = -76.84197263, EPOT = -76.94689823, EKIN = 0.00232668, T = 0.89999886, ResErr = 0.000000, P = 0.3297 GPa, V = 15626.18 ų, t = 0.3 s
0.02312704 GB


########## Step = 1 ##########
H0: 0.088 s
H1: 0.021 s
  rank: 0, Fel = 0.000561
KER: 0.013 s
F AND E: 0.145 s
ETOT = -76.84302146, EPOT = -77.23721095, EKIN = 0.10387677, T = 40.18128011, ResErr = 0.001150, P = 0.3327 GPa, V = 15627.37 ų, t = 0.3 s
0.023129088 GB


########## Step = 2 ##########
H0: 0.088 s
H1: 0.022 s
  rank: 0, Fel = 0.000114
KER: 0.014 s
F AND E: 0.150 s
ETOT = -76.85076490, EPOT = -77.68449109, EKIN = 0.38644605, T = 149.48382956, ResErr = 0.002465, P = 0.3369 GPa, V = 15628.57 ų, t = 0.3 s
0.023130112 GB


########## Step = 3 ##########
H0: 0.088 s
H1: 0.022 s
  rank: 0, Fel = 0.000215
KER: 0.013 s
F AND E: 0.143 s
ETOT = -76.86293229, EPOT = -78.24820325, EKIN = 0.82155879, T = 317.79275253, ResErr 

# 2. Batched MD with PBC and full Coulomb calculations.
### Systems in a batch should have same number of atoms and orbitals. Number of electrons and atom order can be arbitrary.
### Note, Batched mode does not support PME, only full Coulomb. Also no batched open-shell.

In [ ]:
%%time
dftorch_params = {
    "FILENAME": ["COORD_8WATER.xyz"] * 4,
    "CELL": torch.tensor( [[21, 21, 21], [22, 22, 22], [21, 21, 22], [22, 22, 21]], device=device),  # Simulation box vectors in Angstroms
    "SKFPATH": "sk_orig/mio-1-1/mio-1-1/",  # Path to SKF files
    "T_ELECTRONIC": 1000.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.

    "COUL_METHOD": "FULL",
}

device = "cuda"

const = Constants(dftorch_params).to(device)

structure = StructureBatch(dftorch_params, const, device=device)

es_driver = ESDriverBatch(dftorch_params, device=device)
es_driver(structure, const, do_scf=True, verbose=False)
es_driver.calc_forces(structure, const)

DFTB3: False
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
  Initial mu tensor([-1.5453, -1.5453, -1.5453, -1.5453], device='cuda:0')

Starting cycle
Iter 1
Batch 0: Res = 7.373e-01, dEc = 5.513e+00
Batch 1: Res = 7.374e-01, dEc = 5.514e+00
Batch 2: Res = 7.373e-01, dEc = 5.513e+00
Batch 3: Res = 7.373e-01, dEc = 5.513e+00
Iter 2
Batch 0: Res = 5.458e-01, dEc = 1.705e+00
Batch 1: Res = 5.459e-01, dEc = 1.705e+00
Batch 2: Res = 5.459e-01, dEc = 1.705e+00
Batch 3: Res = 5.459e-01, dEc = 1.705e+00
Iter 3
Batch 0: Res = 1.461e-02, dEc = 1.590e-02
Batch 1: Res = 1.460e-02, dEc = 1.590e-02
Batch 2: Res = 1.460e-02, dEc = 1.590e-02
Batch 3: Res = 1.461e-02, dEc = 1.590e-02
Iter 4
Batch 0: Res = 2.943e-03, dEc = 1.823e-02
Batch 1: Res = 2.943e-03, dEc = 1.823e-02
Batch 2: Res = 2.943e-03, dEc = 1.823e-02
Batch 3: Res = 2.943e-03, dEc = 1.823e-02
Iter 5
Batch 0: Res = 4.307e-03, dEc = 1.125e-02
Batch 1: Res = 4.306e-03, dEc = 1.124e-02
Batch 2: Res = 4.306e-03, dEc = 1.125e-02
Batch 3: Res = 4

In [11]:
torch.manual_seed(0)
temperature_K = torch.tensor([20.0, 30.0, 30.0, 30.0], device=structure.device)
mdDriver = MDXLBatch(es_driver, const, temperature_K=temperature_K)
mdDriver.enable_langevin(gamma=0.02)  # thermostat
mdDriver.run(
    structure,
    dftorch_params,
    num_steps=5,
    dt=0.3,
    dump_interval=5,
    traj_filename="batch_md_trj.xyz",
)

########## Step = 0 ##########
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
H0: 2.153 s
H1: 0.008 s
  rank: 0, batch 0, Fel = 0.000013
  rank: 0, batch 1, Fel = 0.000014
  rank: 0, batch 2, Fel = 0.000012
  rank: 0, batch 3, Fel = 0.000013
  Not converged: 0
KER: 0.003 s
F AND E: 0.002 s
ETOT = -110.60058054, EPOT = -886.48165114, EKIN = 0.05687440, T = 18.33331009, ResErr = 0.000000, t = 2.2 s
ETOT = -110.57159404, EPOT = -886.46293555, EKIN = 0.08531159, T = 27.49996514, ResErr = 0.000000, t = 2.2 s
ETOT = -110.57182773, EPOT = -886.44544501, EKIN = 0.08531159, T = 27.49996514, ResErr = 0.000000, t = 2.2 s
ETOT = -110.57190710, EPOT = -886.45803150, EKIN = 0.08531159, T = 27.49996514, ResErr = 0.000000, t = 2.2 s
0.02626304 GB


########## Step = 1 ##########
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
H0: 1.224 s
H1: 0.008 s
  rank: 0, batch 0, Fel = 0.000020
  rank: 0, batch 1, Fel = 0.000020
  rank: 0, batch 2, Fel = 0.000021
  rank: 0, batch 3, Fel = 0.000022
  Not converged

# 3. Open-Shell MD.
### Turn on PBC if necessary. No batch mode for open-shell
## First, SCF and forces

In [ ]:
%%time
dftorch_params = {
    "FILENAME": "O2.xyz",
    "SKFPATH": "sk_orig/mio-1-1/mio-1-1/",  # Path to SKF files
    "T_ELECTRONIC": 500.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.

    "UNRESTRICTED": True,
    "SPIN_POL": 2,  # Spin polarization (N_alpha - N_beta). Default is 0 (non-magnetic).
    "COUL_METHOD": "!PME",  # 'FULL' for full coulomb matrix, 'PME' for PME method
}

# Initial data, load atoms and coordinates, etc in COORD.dat
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create constants container. Set path to SKF files.
const = Constants(dftorch_params).to(device)

structure1 = Structure(dftorch_params, const,device=device)

es_driver = ESDriver(
    dftorch_params, device=device
)
es_driver(structure1, const, do_scf=True)
es_driver.calc_forces(structure1, const)  # Calculate forces after SCF

DFTB3: False
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
### Do _scf ###
  Initial dm_fermi

Starting cycle
Iter 1
Res = 0.000000000, dEc = 0.000000000, t = 0.0 s

CPU times: user 1.57 s, sys: 30.6 ms, total: 1.6 s
Wall time: 294 ms


In [8]:
Ha = 0.0367493  # correct eV → Ha conversion
print(f"  {'net spin':22s} {structure1.net_spin_sr.sum().item():12.4f}")
print(f"  {'Chemical Potential':22s} {structure1.mu0 * Ha} Ha  ({structure1.mu0} Ev)")
print(f"{'Energy Components':─^52}")
print(
    f"  {'E_total':22s} {structure1.e_tot * Ha:12.6f} Ha  ({structure1.e_tot:12.6f} Ev)"
)
print(
    f"  {'E_band':22s} {structure1.e_band0 * Ha:12.6f} Ha  ({structure1.e_band0:12.6f} Ev)"
)
print(
    f"  {'E_coulomb':22s} {structure1.e_coul * Ha:12.6f} Ha  ({structure1.e_coul:12.6f} Ev)"
)
print(
    f"  {'E_repulsion':22s} {structure1.e_repulsion * Ha:12.6f} Ha  ({structure1.e_repulsion:12.6f} Ev)"
)
print(
    f"  {'E_entropy (-TS)':22s} {structure1.e_entropy * Ha:12.6f} Ha  ({structure1.e_entropy:12.6f} Ev)"
)
print(
    f"  {'E_spin':22s} {structure1.e_spin.item() * Ha:12.6f} Ha  ({structure1.e_spin.item():12.6f} eV)"
)
print(f"{'─' * 52}")
print(
    f"  {'E_free (F=E-TS)':22s} {(structure1.e_tot - structure1.e_entropy) * Ha:12.6f} Ha"
)

  net spin                     2.0000
  Chemical Potential     tensor([ 0.2212, -0.2875], device='cuda:0') Ha  (tensor([ 6.0182, -7.8239], device='cuda:0') Ev)
─────────────────Energy Components──────────────────
  E_total                   -0.331896 Ha  (   -9.031347 Ev)
  E_band                    -0.462179 Ha  (  -12.576546 Ev)
  E_coulomb                  0.000000 Ha  (    0.000000 Ev)
  E_repulsion                0.158084 Ha  (    4.301676 Ev)
  E_entropy (-TS)            0.000000 Ha  (    0.000000 Ev)
  E_spin                    -0.027800 Ha  (   -0.756477 eV)
────────────────────────────────────────────────────
  E_free (F=E-TS)           -0.331896 Ha


In [9]:
structure1.q_tot_atom

tensor([-7.2164e-15, -7.7161e-15], device='cuda:0')

In [10]:
# net spin shell-resolved
structure1.net_spin_sr

tensor([5.5511e-16, 1.0000e+00, 1.2212e-15, 1.0000e+00], device='cuda:0')

## MD

In [16]:
torch.manual_seed(0)
temperature_K = torch.tensor(300.0, device=structure1.device)
mdDriver = MDXLOS(es_driver, const, temperature_K=temperature_K)
# mdDriver.NoRank = True
# Set number of steps, time step (fs), dump interval and trajectory filename
mdDriver.run(
    structure1,
    dftorch_params,
    num_steps=5,
    dt=0.2,
    dump_interval=5,
    traj_filename="md_trj.xyz",
)

########## Step = 0 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.123 s
H1: 0.003 s
  rank: 0, Fel = 0.000000
KER: 0.005 s
F AND E: 0.004 s
ETOT = -8.99256860, EPOT = -9.02871676, EKIN = 0.03877800, T = 149.99980985,  NS = 2.0000, ResErr = 0.000000, t = 0.1 s
0.02337024 GB


########## Step = 1 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.093 s
H1: 0.003 s
  rank: 0, Fel = 0.000000
KER: 0.005 s
F AND E: 0.004 s
ETOT = -8.99256612, EPOT = -9.02587471, EKIN = 0.03615064, T = 139.83674359,  NS = 2.0000, ResErr = 0.001184, t = 0.1 s
0.023369728 GB


########## Step = 2 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.092 s
H1: 0.003 s
  rank: 0, Fel = 0.000000
KER: 0.005 s
F AND E: 0.004 s
ETOT = -8.99256332, EPOT = -9.02286628, EKIN = 0.03331139, T = 128.85403952,  NS = 2.0000, ResErr = 0.000171, t = 0.1 s
0.02337024 GB


########## Step = 3 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.093 s
H1: 0.003 s
  rank:

# 4. DFTB3.
### Full (off-diagonal) and diagonal-only third corrections order are available.

In [ ]:
%%time
dftorch_params = {
    "FILENAME": "O2.xyz",
    "SKFPATH": "sk_orig/3ob-3-1/",  # Path to SKF files
    "T_ELECTRONIC": 500.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.

    "UNRESTRICTED": True,
    "SPIN_POL": 2,  # Spin polarization (N_alpha - N_beta). Default is 0 (non-magnetic).

    "COUL_METHOD": "!PME",  # 'FULL' for full coulomb matrix, 'PME' for PME method

    "DFTB3": True,  # Set to True to enable DFTB3 corrections. Default is False (DFTB2).
    # "dftb3_diagonal_only": True,  # If True, use diagonal-only third-order corrections. Otherwise, use full (off-diagonal) third-order corrections. Default is False (full corrections).
}

device = "cuda" if torch.cuda.is_available() else "cpu"

const = Constants(dftorch_params).to(device)

structure1 = Structure(dftorch_params, const, device=device)

es_driver = ESDriver(dftorch_params, device=device)
es_driver(structure1, const, do_scf=True)
es_driver.calc_forces(structure1, const)  # Calculate forces after SCF

DFTB3: True
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
### Do _scf ###
  Initial dm_fermi

Starting cycle
Iter 1
Res = 0.000000000, dEc = 0.000000000, t = 0.0 s

CPU times: user 1.8 s, sys: 16.6 ms, total: 1.81 s
Wall time: 308 ms


In [12]:
Ha = 0.0367493  # correct eV → Ha conversion
print(f"  {'net spin':22s} {structure1.net_spin_sr.sum().item():12.4f}")
print(f"  {'Chemical Potential':22s} {structure1.mu0 * Ha} Ha  ({structure1.mu0} Ev)")
print(f"{'Energy Components':─^52}")
print(
    f"  {'E_total':22s} {structure1.e_tot * Ha:12.6f} Ha  ({structure1.e_tot:12.6f} Ev)"
)
print(
    f"  {'E_band':22s} {structure1.e_band0 * Ha:12.6f} Ha  ({structure1.e_band0:12.6f} Ev)"
)
print(
    f"  {'E_coulomb':22s} {structure1.e_coul * Ha:12.6f} Ha  ({structure1.e_coul:12.6f} Ev)"
)
print(
    f"  {'E_repulsion':22s} {structure1.e_repulsion * Ha:12.6f} Ha  ({structure1.e_repulsion:12.6f} Ev)"
)
print(
    f"  {'E_entropy (-TS)':22s} {structure1.e_entropy * Ha:12.6f} Ha  ({structure1.e_entropy:12.6f} Ev)"
)
print(
    f"  {'E_spin':22s} {structure1.e_spin.item() * Ha:12.6f} Ha  ({structure1.e_spin.item():12.6f} eV)"
)
print(f"{'─' * 52}")
print(
    f"  {'E_free (F=E-TS)':22s} {(structure1.e_tot - structure1.e_entropy) * Ha:12.6f} Ha"
)

  net spin                     2.0000
  Chemical Potential     tensor([ 0.2020, -0.2871], device='cuda:0') Ha  (tensor([ 5.4976, -7.8110], device='cuda:0') Ev)
─────────────────Energy Components──────────────────
  E_total                   -0.303920 Ha  (   -8.270081 Ev)
  E_band                    -0.406516 Ha  (  -11.061881 Ev)
  E_coulomb                  0.000000 Ha  (    0.000000 Ev)
  E_repulsion                0.130447 Ha  (    3.549637 Ev)
  E_entropy (-TS)            0.000000 Ha  (    0.000000 Ev)
  E_spin                    -0.027850 Ha  (   -0.757837 eV)
────────────────────────────────────────────────────
  E_free (F=E-TS)           -0.303920 Ha


In [19]:
structure1.q_tot_atom

tensor([-5.4956e-15, -6.3283e-15], device='cuda:0')

In [20]:
# net spin shell-resolved
structure1.net_spin_sr

tensor([9.9920e-16, 1.0000e+00, 3.3307e-16, 1.0000e+00], device='cuda:0')

# 5. Backprop.
## Backprop is only supported for full coulomb summation (no PME).
### 1. Through coordinates.

In [ ]:
dftorch_params = {
    "FILENAME": ["COORD_8WATER.xyz"] * 4,
    "CELL": torch.tensor( [[21, 21, 21], [22, 22, 22], [21, 21, 22], [22, 22, 21]], device=device),  # Simulation box vectors in Angstroms
    "SKFPATH": "sk_orig/mio-1-1/mio-1-1/",  # Path to SKF files
    "T_ELECTRONIC": 1000.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.

    "COUL_METHOD": "FULL",

    "GRAD_XYZ": True,
}

device = "cuda"

const = Constants(dftorch_params).to(device)

structure = StructureBatch(
    dftorch_params,
    const,
    device=device,
)

es_driver = ESDriverBatch(
    dftorch_params, device=device
)
es_driver(structure, const, do_scf=True, verbose=False)
es_driver.calc_forces(structure, const)

DFTB3: False
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
  Initial mu tensor([-1.5453, -1.5453, -1.5453, -1.5453], device='cuda:0',
       grad_fn=<MulBackward0>)

Starting cycle
Iter 1
Batch 0: Res = 7.373e-01, dEc = 5.513e+00
Batch 1: Res = 7.374e-01, dEc = 5.514e+00
Batch 2: Res = 7.373e-01, dEc = 5.513e+00
Batch 3: Res = 7.373e-01, dEc = 5.513e+00
Iter 2
Batch 0: Res = 5.458e-01, dEc = 1.705e+00
Batch 1: Res = 5.459e-01, dEc = 1.705e+00
Batch 2: Res = 5.459e-01, dEc = 1.705e+00
Batch 3: Res = 5.459e-01, dEc = 1.705e+00
Iter 3
Batch 0: Res = 1.461e-02, dEc = 1.590e-02
Batch 1: Res = 1.460e-02, dEc = 1.590e-02
Batch 2: Res = 1.460e-02, dEc = 1.590e-02
Batch 3: Res = 1.461e-02, dEc = 1.590e-02
Iter 4
Batch 0: Res = 2.943e-03, dEc = 1.823e-02
Batch 1: Res = 2.943e-03, dEc = 1.823e-02
Batch 2: Res = 2.943e-03, dEc = 1.823e-02
Batch 3: Res = 2.943e-03, dEc = 1.823e-02
Iter 5
Batch 0: Res = 4.307e-03, dEc = 1.125e-02
Batch 1: Res = 4.306e-03, dEc = 1.124e-02
Batch 2: Res = 4.306e-03, d

In [22]:
grads = torch.autograd.grad(
    structure.e_tot.sum(), [structure.RX, structure.RY, structure.RZ]
)
forces_backprop = -torch.stack(grads, dim=1)

# compare forces from backprop with analytical forces from ESDriver.
(structure.f_tot - forces_backprop).abs().max()

tensor(3.9122e-08, device='cuda:0', grad_fn=<MaxBackward1>)

### 2. Through DFTB parameters (on-site orbital energies).

In [ ]:
dftorch_params = {
    "FILENAME": ["COORD_8WATER.xyz"] * 4,
    "CELL": torch.tensor( [[21, 21, 21], [22, 22, 22], [21, 21, 22], [22, 22, 21]], device=device),  # Simulation box vectors in Angstroms
    "SKFPATH": "sk_orig/mio-1-1/mio-1-1/",  # Path to SKF files
    "T_ELECTRONIC": 1000.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.

    "COUL_METHOD": "FULL",
    
    "GRAD_PARAM": True,
}
# Initial data, load atoms and coordinates, etc in COORD.dat
device = "cuda"

const = Constants(
    dftorch_params
).to(device)

structure = StructureBatch(
    dftorch_params,
    const,
    device=device,
)

es_driver = ESDriverBatch(
    dftorch_params, device=device
)
es_driver(structure, const, do_scf=True, verbose=False)
es_driver.calc_forces(structure, const)

DFTB3: False
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
  Initial mu tensor([-1.5453, -1.5453, -1.5453, -1.5453], device='cuda:0',
       grad_fn=<MulBackward0>)

Starting cycle
Iter 1
Batch 0: Res = 7.373e-01, dEc = 5.513e+00
Batch 1: Res = 7.374e-01, dEc = 5.514e+00
Batch 2: Res = 7.373e-01, dEc = 5.513e+00
Batch 3: Res = 7.373e-01, dEc = 5.513e+00
Iter 2
Batch 0: Res = 5.458e-01, dEc = 1.705e+00
Batch 1: Res = 5.459e-01, dEc = 1.705e+00
Batch 2: Res = 5.459e-01, dEc = 1.705e+00
Batch 3: Res = 5.459e-01, dEc = 1.705e+00
Iter 3
Batch 0: Res = 1.461e-02, dEc = 1.590e-02
Batch 1: Res = 1.460e-02, dEc = 1.590e-02
Batch 2: Res = 1.460e-02, dEc = 1.590e-02
Batch 3: Res = 1.461e-02, dEc = 1.590e-02
Iter 4
Batch 0: Res = 2.943e-03, dEc = 1.823e-02
Batch 1: Res = 2.943e-03, dEc = 1.823e-02
Batch 2: Res = 2.943e-03, dEc = 1.823e-02
Batch 3: Res = 2.943e-03, dEc = 1.823e-02
Iter 5
Batch 0: Res = 4.307e-03, dEc = 1.125e-02
Batch 1: Res = 4.306e-03, dEc = 1.124e-02
Batch 2: Res = 4.306e-03, d

In [24]:
grads = torch.autograd.grad(structure.e_tot.sum(), [const.Es, const.Ep])
grads = torch.stack(grads, dim=0)

In [25]:
print("dE/dEs_H:", grads[0, 1].item())
print("dE/dEs_O:", grads[0, 8].item())
print("dE/dEp_O:", grads[1, 8].item())

dE/dEs_H: -36.14599437362467
dE/dEs_O: -11.85421571715753
dE/dEp_O: 11.815163945217954
