In [1]:
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# %                   SCF-TB - PROXY APPLICATION                      %
# %                   A.M.N. Niklasson, M. Kulichenko. T1, LANL       %
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# % Total Energy Function:                                            %
# % E = 2Tr[H0(D-D0)] + (1/2)*sum_i U_i q_i^2 +                       %
# %      + (1/2)sum_{i,j (i!=j)} q_i C_{ij} q_j - Efield*dipole       %
# % dipole = sum_i R_{i} q_i                                          %
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

import torch
import warnings
import logging
import os

# to disable torchdynamo completely. Faster for smaller systems and single-point calculations.
os.environ["TORCHDYNAMO_DISABLE"] = "1"  # hard-disable capture

from dftorch import (
    Constants,
    Structure,
    StructureBatch,
    MDXL,
    MDXLBatch,
    MDXLOS,
    ESDriver,
    ESDriverBatch,
)

### Configure torch and torch.compile ###
# Silence warnings and module logs
warnings.filterwarnings("ignore")
os.environ["TORCH_LOGS"] = ""  # disable PT2 logging
os.environ["TORCHINDUCTOR_VERBOSE"] = "0"
os.environ["TORCHDYNAMO_VERBOSE"] = "0"
logging.getLogger("torch.fx").setLevel(logging.CRITICAL)
logging.getLogger("torch.fx.experimental.symbolic_shapes").setLevel(logging.CRITICAL)
logging.getLogger("torch.fx.experimental.recording").setLevel(logging.CRITICAL)
# Enable dynamic shape capture for dynamo
torch._dynamo.config.capture_dynamic_output_shape_ops = True
# default data type
torch.set_default_dtype(torch.float64)

torch.cuda.empty_cache()

# MD with PBC and PME
### Note, cutoff must be <= (0.5 x cell dimensions) if using PME.
### Also, do not use PME without PBC.

## First, SCF and forces

In [2]:
%%time
dftorch_params = {
    "coul_method": "PME",  # 'FULL' for full coulomb matrix, 'PME' for PME method
    "Coulomb_acc": 5e-5,  # Coulomb accuracy for full coulomb calcs or t_err for PME
    "cutoff": 12.0,  # Coulomb cutoff
    "PME_order": 4,  # Ignored for FULL coulomb method
    "SCF_MAX_ITER": 100,  # Maximum number of SCF iterations
    "SCF_TOL": 1e-6,  # SCF convergence tolerance on density matrix
    "SCF_ALPHA": 0.4,  # Scaled delta function coefficient. Acts as linear mixing coefficient used before Krylov acceleration starts.
    "KRYLOV_MAXRANK": 20,  # Maximum Krylov subspace rank
    "KRYLOV_TOL": 1e-6,  # Krylov subspace convergence tolerance in SCF
    "KRYLOV_TOL_MD": 1e-4,  # Krylov subspace convergence tolerance in MD SCF
    "KRYLOV_START": 4,  # Number of initial SCF iterations before starting Krylov acceleration
    "h_damp_exp": 4.0,  # Exponential damping factor for hydrogen bonds. Default is None.
    # optional:
    # "UNRESTRICTED": False, # Whether to perform unrestricted (spin-polarized) calculation. Default is False (restricted).
    # "SHARED_MU": False, # Whether to use shared chemical potential for alpha and beta spin channels. Default is False (per-channel chemical potentials).
    # "BROKEN_SYM": False, # if True, mix 10 % of lumo in homo at initialization.
    # "d3_params": {"s6": 1.0, "s8": 0.5883, "a1": 0.5719, "a2": 3.6107}, # D3 dispersion parameters
    # "solvent_param_file": "sk_orig/mio-1-1/mio-1-1/solvation/param_gbsa1_h2o.txt",
    # "solvation_model": "gbsa", # gbsa (default) or alpb
    # "h5_params": {
    #     "r_scaling": 0.714,
    #     "w_scaling": 0.25,
    #     "h5_scaling": {8: 0.06, 7: 0.18, 16: 0.21},  # O, N, S
    # }, # H5 correction. Default is None. Mutually exclusive with h_damp_exp.
    # 'ANDERSON_DEPTH': 10 # Anderson extrapolation depth for MD SCF. Default is 10. Set to 0 to disable Anderson extrapolation and use simple linear mixing in MD SCF.
}

# Initial data, load atoms and coordinates, etc in COORD.dat
device = "cuda" if torch.cuda.is_available() else "cpu"
filename = "COORD.xyz"  # Solvated acetylacetone and glycine molecules in H20, Na, Cl
LBox = torch.tensor(
    [[25.0, 0.0, 0.0], [0.0, 25.0, 0.0], [0.0, 0.0, 25.0]], device=device
)  # Simulation box size in Angstroms. Only cubic boxes supported for now.
# Create constants container. Set path to SKF files.
const = Constants(
    filename,
    "sk_orig/mio-1-1/mio-1-1/",
    magnetic_hubbard_ldep=False,
).to(device)

# Create structure object. Define total charge and electronic temperature.
structure1 = Structure(filename, LBox, const, charge=0, Te=1000.0, device=device)

# Create ESDriver object and run SCF calculation
# electronic_rcut and repulsive_rcut are in Angstroms.
# They should be >= cutoffs defined in SKF files for the element pair with largest cutoff present in the system.
es_driver = ESDriver(
    dftorch_params, electronic_rcut=8.0, repulsive_rcut=6.0, device=device
)
es_driver(structure1, const, do_scf=True)
es_driver.calc_forces(structure1, const)  # Calculate forces after SCF
es_driver.calc_stress(structure1, const)  # Calculate stress after SCF

DFTB3: False


### Do _scf ###
  Initial dm_fermi
  Initial mu = 0.1306

Starting cycle
Iter 1
Res = 0.179150828, dEc = 0.539417818, t = 0.0 s

Iter 2
Res = 0.108650501, dEc = 0.428064525, t = 0.0 s

Iter 3
Res = 0.019281416, dEc = 0.976824189, t = 0.0 s

Iter 4
Res = 0.000967137, dEc = 0.237414310, t = 0.0 s

Iter 5
  rank: 0, Fel = 0.000005
  rank: 1, Fel = 0.000001
Res = 0.000070052, dEc = 0.004955299, t = 0.1 s

Iter 6
  rank: 0, Fel = 0.000000
Res = 0.000001781, dEc = 0.000472133, t = 0.0 s

Iter 7
  rank: 0, Fel = 0.000000
Res = 0.000000325, dEc = 0.000007184, t = 0.0 s

CPU times: user 4.68 s, sys: 537 ms, total: 5.22 s
Wall time: 1.9 s


In [3]:
Ha = 0.0367493  # correct eV → Ha conversion
# print(f"  {'net spin':22s} {structure1.net_spin_sr.sum().item():12.4f}")
print(
    f"  {'Chemical Potential':22s} {structure1.mu0 * Ha:12.6f} Ha  ({structure1.mu0:12.6f} Ev)"
)
print(f"{'Energy Components':─^52}")
print(
    f"  {'E_total':22s} {structure1.e_tot * Ha:12.6f} Ha  ({structure1.e_tot:12.6f} Ev)"
)
print(
    f"  {'E_band':22s} {structure1.e_band0 * Ha:12.6f} Ha  ({structure1.e_band0:12.6f} Ev)"
)
print(
    f"  {'E_coulomb':22s} {structure1.e_coul * Ha:12.6f} Ha  ({structure1.e_coul:12.6f} Ev)"
)
print(
    f"  {'E_repulsion':22s} {structure1.e_repulsion * Ha:12.6f} Ha  ({structure1.e_repulsion:12.6f} Ev)"
)
print(
    f"  {'E_entropy (-TS)':22s} {structure1.e_entropy * Ha:12.6f} Ha  ({structure1.e_entropy:12.6f} Ev)"
)
# print(f"  {'E_spin':22s} {structure1.e_spin.item()*Ha:12.6f} Ha  ({structure1.e_spin.item():12.6f} eV)")
print(f"{'─' * 52}")
print(
    f"  {'E_free (F=E-TS)':22s} {(structure1.e_tot - structure1.e_entropy) * Ha:12.6f} Ha"
)

  Chemical Potential         0.014260 Ha  (    0.388044 Ev)
─────────────────Energy Components──────────────────
  E_total                   -2.823974 Ha  (  -76.844285 Ev)
  E_band                    -2.805488 Ha  (  -76.341254 Ev)
  E_coulomb                 -0.009232 Ha  (   -0.251229 Ev)
  E_repulsion               -0.009254 Ha  (   -0.251802 Ev)
  E_entropy (-TS)            0.000000 Ha  (    0.000000 Ev)
────────────────────────────────────────────────────
  E_free (F=E-TS)           -2.823974 Ha


In [4]:
# total forces
structure1.f_tot

tensor([[-7.3038, -0.4120, -5.5981, -2.6595, -1.3460,  0.8168,  0.9404, -5.0542,
         -1.9465,  5.3640,  0.5464,  1.0173, -5.1237, -1.8800,  5.2904, 10.0700,
          1.6909, -0.8837,  0.6773,  5.7940],
        [ 0.2056, -0.1111, -0.6874, -0.4509,  0.8452,  0.6972, -0.1738, -0.6375,
         -0.9824,  1.0365,  0.7354, -0.2126, -0.7517, -0.8772,  1.1052,  0.4230,
          0.0638, -0.9181, -0.4811,  1.1719],
        [-2.0592, -0.1140, -0.4980, -0.8283,  0.6982,  0.2309,  0.0278, -0.8519,
         -0.9190,  1.4814,  0.1443, -0.0216, -0.7520, -0.9496,  1.5775,  1.0394,
          0.1708,  0.3830, -0.2174,  1.4577]], device='cuda:0')

In [6]:
# total stresses
structure1.stress_tot

tensor([[-0.0046,  0.0003, -0.0006],
        [ 0.0003, -0.0007, -0.0001],
        [-0.0006, -0.0001, -0.0008]], device='cuda:0')

In [7]:
# charges:
structure1.q

tensor([ 0.4848, -0.1008, -0.1642, -0.1252, -0.0984,  0.6170, -0.1163, -0.1613,
        -0.1223, -0.2187,  0.6144, -0.1181, -0.1620, -0.1208, -0.2180,  0.5056,
        -0.1133, -0.0794, -0.0835, -0.2193], device='cuda:0')

In [8]:
# MO coeffs
structure1.Q

tensor([[ 0.2888, -0.4240,  0.4409,  ..., -0.2147,  0.1975, -0.1110],
        [ 0.0683, -0.0498, -0.0511,  ..., -0.0042,  0.0565, -0.0565],
        [-0.0008,  0.0011, -0.0032,  ..., -0.0147,  0.0663, -0.0566],
        ...,
        [ 0.0608,  0.1374,  0.1938,  ...,  0.1116,  0.0842,  0.0377],
        [ 0.0672,  0.1501,  0.2073,  ...,  0.2069,  0.1590,  0.0782],
        [ 0.1518,  0.2448,  0.1753,  ...,  0.3422,  0.4165,  0.2993]],
       device='cuda:0')

## MD

In [9]:
torch.manual_seed(0)
temperature_K = torch.tensor(1.0, device=structure1.device)
mdDriver = MDXL(es_driver, const, temperature_K=temperature_K)

mdDriver.enable_langevin(gamma=0.02)  # thermostat. also needed for proper NPT
mdDriver.enable_barostat(  # barostat
    target_pressure=0.0,  # GPa
    tau=200.0,  # fs
    isotropic=True,
    compressibility=4.57e-5,  # 1/bar (water at 300 K)
)

# Set number of steps, time step (fs), dump interval and trajectory filename
mdDriver.run(
    structure1,
    dftorch_params,
    num_steps=5,
    dt=0.3,
    dump_interval=5,
    traj_filename="md_trj.xyz",
)

########## Step = 0 ##########
H0: 0.090 s
H1: 0.027 s
  rank: 0, Fel = 0.000468
  rank: 1, Fel = 0.000038
KER: 0.029 s
F AND E: 0.159 s
ETOT = -76.84195832, EPOT = -76.94688390, EKIN = 0.00232668, T = 0.89999886, ResErr = 0.000000, P = 0.3297 GPa, V = 15626.18 ų, t = 0.3 s
0.02166016 GB


########## Step = 1 ##########
H0: 0.114 s
H1: 0.025 s
  rank: 0, Fel = 0.000917
  rank: 1, Fel = 0.000071
KER: 0.030 s
F AND E: 0.140 s
ETOT = -76.84300711, EPOT = -77.23722219, EKIN = 0.10387678, T = 40.18128609, ResErr = 0.001150, P = 0.3327 GPa, V = 15627.36 ų, t = 0.3 s
0.021662208 GB


########## Step = 2 ##########
H0: 0.087 s
H1: 0.026 s
  rank: 0, Fel = 0.000503
  rank: 1, Fel = 0.000037
KER: 0.029 s
F AND E: 0.140 s
ETOT = -76.85074484, EPOT = -77.68451576, EKIN = 0.38647736, T = 149.49593908, ResErr = 0.002305, P = 0.3369 GPa, V = 15628.57 ų, t = 0.3 s
0.021663232 GB


########## Step = 3 ##########
H0: 0.087 s
H1: 0.026 s
  rank: 0, Fel = 0.000167
  rank: 1, Fel = 0.000011
KER: 0.032 s

# Batched MD with PBC and full Coulomb calculations.
### Systems in a batch should have same number of atoms and orbitals. Number of electrons and atom order can be arbitrary.
### Note, Batched mode does not support PME, only full Coulomb. Also no batched open-shell.

In [12]:
%%time
dftorch_params = {
    "coul_method": "FULL",
    "Coulomb_acc": 1e-5,  # coulomb accuracy for full coulomb calcs or t_err for PME
    "cutoff": 10.0,  # coulomb cutoff
    "PME_order": 4,
    "SCF_MAX_ITER": 20,
    "SCF_TOL": 1e-6,
    "SCF_ALPHA": 0.1,  # Linear mixing coefficient used before Krylov acceleration starts.
    "KRYLOV_MAXRANK": 20,
    "KRYLOV_TOL": 1e-6,
    "KRYLOV_TOL_MD": 1e-4,
    "KRYLOV_START": 10,
}

# Initial data, load atoms and coordinates, etc in COORD.dat
device = "cuda"

filename = ["COORD_8WATER.xyz"] * 4
LBox = torch.tensor(
    [[21, 21, 21], [22, 22, 22], [21, 21, 22], [22, 22, 21]], device=device
)

const = Constants(filename, "sk_orig/mio-1-1/mio-1-1/").to(device)

structure = StructureBatch(filename, LBox, const, charge=0, Te=1000.0, device=device)

es_driver = ESDriverBatch(
    dftorch_params, electronic_rcut=8.0, repulsive_rcut=6.0, device=device
)
es_driver(structure, const, do_scf=True, verbose=False)
es_driver.calc_forces(structure, const)

DFTB3: False
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
  Initial mu tensor([-1.5453, -1.5453, -1.5453, -1.5453], device='cuda:0')

Starting cycle
Iter 1
Batch 0: Res = 7.373e-01, dEc = 5.513e+00
Batch 1: Res = 7.374e-01, dEc = 5.514e+00
Batch 2: Res = 7.373e-01, dEc = 5.513e+00
Batch 3: Res = 7.373e-01, dEc = 5.513e+00
Iter 2
Batch 0: Res = 5.458e-01, dEc = 1.705e+00
Batch 1: Res = 5.459e-01, dEc = 1.705e+00
Batch 2: Res = 5.459e-01, dEc = 1.705e+00
Batch 3: Res = 5.459e-01, dEc = 1.705e+00
Iter 3
Batch 0: Res = 1.461e-02, dEc = 1.590e-02
Batch 1: Res = 1.460e-02, dEc = 1.590e-02
Batch 2: Res = 1.460e-02, dEc = 1.590e-02
Batch 3: Res = 1.461e-02, dEc = 1.590e-02
Iter 4
Batch 0: Res = 2.943e-03, dEc = 1.823e-02
Batch 1: Res = 2.943e-03, dEc = 1.823e-02
Batch 2: Res = 2.943e-03, dEc = 1.823e-02
Batch 3: Res = 2.943e-03, dEc = 1.823e-02
Iter 5
Batch 0: Res = 4.307e-03, dEc = 1.125e-02
Batch 1: Res = 4.306e-03, dEc = 1.124e-02
Batch 2: Res = 4.306e-03, dEc = 1.125e-02
Batch 3: Res = 4

In [13]:
torch.manual_seed(0)
temperature_K = torch.tensor([20.0, 30.0, 30.0, 30.0], device=structure.device)
mdDriver = MDXLBatch(es_driver, const, temperature_K=temperature_K)
mdDriver.enable_langevin(gamma=0.02)  # thermostat
mdDriver.run(
    structure,
    dftorch_params,
    num_steps=5,
    dt=0.3,
    dump_interval=5,
    traj_filename="batch_md_trj.xyz",
)

########## Step = 0 ##########
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
H0: 2.133 s
H1: 0.008 s
  rank: 0, batch 0, Fel = 0.000013
  rank: 0, batch 1, Fel = 0.000014
  rank: 0, batch 2, Fel = 0.000012
  rank: 0, batch 3, Fel = 0.000013
  Not converged: 0
KER: 0.004 s
F AND E: 0.002 s
ETOT = -110.60058054, EPOT = -886.48165114, EKIN = 0.05687440, T = 18.33331009, ResErr = 0.000000, t = 2.2 s
ETOT = -110.57159404, EPOT = -886.46293555, EKIN = 0.08531159, T = 27.49996514, ResErr = 0.000000, t = 2.2 s
ETOT = -110.57182773, EPOT = -886.44544501, EKIN = 0.08531159, T = 27.49996514, ResErr = 0.000000, t = 2.2 s
ETOT = -110.57190710, EPOT = -886.45803150, EKIN = 0.08531159, T = 27.49996514, ResErr = 0.000000, t = 2.2 s
0.02618624 GB


########## Step = 1 ##########
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
H0: 1.228 s
H1: 0.008 s
  rank: 0, batch 0, Fel = 0.000020
  rank: 0, batch 1, Fel = 0.000020
  rank: 0, batch 2, Fel = 0.000021
  rank: 0, batch 3, Fel = 0.000022
  Not converged

# 3. Open-Shell MD.
### Turn on PBC if necessary
### No batch mode for open-shell
## First, SCF and forces

In [14]:
%%time
dftorch_params = {
    "UNRESTRICTED": True,
    "SHARED_MU": False,  # if True, use shared chemical potential for both spin channels in unrestricted calculations. Otherwise, use separate chemical potentials for each spin channel.
    "BROKEN_SYM": False,  # if True, mix 10 % of lumo in homo at initialization
    "coul_method": "!PME",  # 'FULL' for full coulomb matrix, 'PME' for PME method
    "Coulomb_acc": 5e-5,  # Coulomb accuracy for full coulomb calcs or t_err for PME
    "cutoff": 100000.0,  # Coulomb cutoff. If no PBC used, should be large enough to enable all-to-all coulomb summation.
    "PME_order": 4,  # Ignored for FULL coulomb method
    "SCF_MAX_ITER": 100,  # Maximum number of SCF iterations
    "SCF_TOL": 5e-6,  # SCF convergence tolerance on density matrix
    "SCF_ALPHA": 0.1,  # Scaled delta function coefficient. Acts as linear mixing coefficient used before Krylov acceleration starts.
    "KRYLOV_MAXRANK": 15,  # Maximum Krylov subspace rank
    "KRYLOV_TOL": 9e-6,  # Krylov subspace convergence tolerance in SCF
    "KRYLOV_TOL_MD": 1e-4,  # Krylov subspace convergence tolerance in MD SCF
    "KRYLOV_START": 10,  # Number of initial SCF iterations before starting Krylov acceleration
}

# Initial data, load atoms and coordinates, etc in COORD.dat
device = "cuda" if torch.cuda.is_available() else "cpu"
filename = "O2.xyz"
LBox = None
# LBox = torch.tensor([45.0, 45.0, 40.0], device=device) # Simulation box size in Angstroms. Only cubic boxes supported for now.

# Create constants container. Set path to SKF files.
const = Constants(
    filename,
    "sk_orig/mio-1-1/mio-1-1/",
    magnetic_hubbard_ldep=False,
).to(device)

# Create structure object. Define total charge and electronic temperature.
# charge=0 and spin_pol need to be specified for open-shell systems.
# spin_pol is the number of unpaired electrons, not multiplicity.
# Shared chemical potential is used for both spin channels, so spin_pol has no effect but needs to be set anyways.
structure1 = Structure(
    filename,
    LBox,
    const,
    charge=0,
    spin_pol=2,
    os=dftorch_params["UNRESTRICTED"],
    Te=500.0,
    device=device,
)

# Create ESDriver object and run SCF calculation
# electronic_rcut and repulsive_rcut are in Angstroms.
# They should be >= cutoffs defined in SKF files for the element pair with largest cutoff present in the system.
es_driver = ESDriver(
    dftorch_params, electronic_rcut=8.0, repulsive_rcut=6.0, device=device
)
es_driver(structure1, const, do_scf=True)
es_driver.calc_forces(structure1, const)  # Calculate forces after SCF

DFTB3: False
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
### Do _scf ###
  Initial dm_fermi

Starting cycle
Iter 1
Res = 0.000000000, dEc = 0.000000000, t = 0.0 s

CPU times: user 1.65 s, sys: 23.1 ms, total: 1.67 s
Wall time: 336 ms


In [15]:
Ha = 0.0367493  # correct eV → Ha conversion
print(f"  {'net spin':22s} {structure1.net_spin_sr.sum().item():12.4f}")
print(f"  {'Chemical Potential':22s} {structure1.mu0 * Ha} Ha  ({structure1.mu0} Ev)")
print(f"{'Energy Components':─^52}")
print(
    f"  {'E_total':22s} {structure1.e_tot * Ha:12.6f} Ha  ({structure1.e_tot:12.6f} Ev)"
)
print(
    f"  {'E_band':22s} {structure1.e_band0 * Ha:12.6f} Ha  ({structure1.e_band0:12.6f} Ev)"
)
print(
    f"  {'E_coulomb':22s} {structure1.e_coul * Ha:12.6f} Ha  ({structure1.e_coul:12.6f} Ev)"
)
print(
    f"  {'E_repulsion':22s} {structure1.e_repulsion * Ha:12.6f} Ha  ({structure1.e_repulsion:12.6f} Ev)"
)
print(
    f"  {'E_entropy (-TS)':22s} {structure1.e_entropy * Ha:12.6f} Ha  ({structure1.e_entropy:12.6f} Ev)"
)
print(
    f"  {'E_spin':22s} {structure1.e_spin.item() * Ha:12.6f} Ha  ({structure1.e_spin.item():12.6f} eV)"
)
print(f"{'─' * 52}")
print(
    f"  {'E_free (F=E-TS)':22s} {(structure1.e_tot - structure1.e_entropy) * Ha:12.6f} Ha"
)

  net spin                     2.0000
  Chemical Potential     tensor([ 0.2212, -0.2875], device='cuda:0') Ha  (tensor([ 6.0182, -7.8239], device='cuda:0') Ev)
─────────────────Energy Components──────────────────
  E_total                   -0.331896 Ha  (   -9.031347 Ev)
  E_band                    -0.462179 Ha  (  -12.576546 Ev)
  E_coulomb                  0.000000 Ha  (    0.000000 Ev)
  E_repulsion                0.158084 Ha  (    4.301676 Ev)
  E_entropy (-TS)            0.000000 Ha  (    0.000000 Ev)
  E_spin                    -0.027800 Ha  (   -0.756477 eV)
────────────────────────────────────────────────────
  E_free (F=E-TS)           -0.331896 Ha


In [16]:
structure1.q_tot_atom

tensor([-7.2164e-15, -7.7161e-15], device='cuda:0')

In [17]:
# net spin shell-resolved
structure1.net_spin_sr

tensor([5.5511e-16, 1.0000e+00, 1.2212e-15, 1.0000e+00], device='cuda:0')

## MD

In [18]:
torch.manual_seed(0)
temperature_K = torch.tensor(300.0, device=structure1.device)
mdDriver = MDXLOS(es_driver, const, temperature_K=temperature_K)
# mdDriver.NoRank = True
# Set number of steps, time step (fs), dump interval and trajectory filename
mdDriver.run(
    structure1,
    dftorch_params,
    num_steps=5,
    dt=0.2,
    dump_interval=5,
    traj_filename="md_trj.xyz",
)

########## Step = 0 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.104 s
H1: 0.004 s
  rank: 0, Fel = 0.000000
KER: 0.006 s
F AND E: 0.006 s
ETOT = -8.99256860, EPOT = -9.02871676, EKIN = 0.03877800, T = 149.99980985,  NS = 2.0000, ResErr = 0.000000, t = 0.1 s
0.026979328 GB


########## Step = 1 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.095 s
H1: 0.004 s
  rank: 0, Fel = 0.000000
KER: 0.006 s
F AND E: 0.006 s
ETOT = -8.99256612, EPOT = -9.02587471, EKIN = 0.03615064, T = 139.83674359,  NS = 2.0000, ResErr = 0.001184, t = 0.1 s
0.02697984 GB


########## Step = 2 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.092 s
H1: 0.004 s
  rank: 0, Fel = 0.000000
KER: 0.006 s
F AND E: 0.006 s
ETOT = -8.99256332, EPOT = -9.02286628, EKIN = 0.03331139, T = 128.85403952,  NS = 2.0000, ResErr = 0.000171, t = 0.1 s
0.026980352 GB


########## Step = 3 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.092 s
H1: 0.004 s
  rank