In [28]:
import torch
import warnings
import os
torch.set_default_dtype(torch.float64)

# To disable torchdynamo completely. Faster for smaller systems and single-point calculations.
ENABLE_TORCH_COMPILE = False
os.environ["DFTORCH_ENABLE_COMPILE"] = "1" if ENABLE_TORCH_COMPILE else "0"
if ENABLE_TORCH_COMPILE:
    os.environ.pop("TORCHDYNAMO_DISABLE", None)
else:
    os.environ["TORCHDYNAMO_DISABLE"] = "1"

from dftorch import (
    Constants,
    Structure,
    StructureBatch,
    MDXL,
    MDXLBatch,
    ESDriver,
    ESDriverBatch,
)
warnings.filterwarnings("ignore")

In [ ]:
import torch
import os
torch.set_default_dtype(torch.float64)

# To disable torchdynamo completely. Faster for smaller systems and single-point calculations. Set to True to test torch.compile.
ENABLE_TORCH_COMPILE = False
os.environ["DFTORCH_ENABLE_COMPILE"] = "1" if ENABLE_TORCH_COMPILE else "0"
if ENABLE_TORCH_COMPILE: os.environ.pop("TORCHDYNAMO_DISABLE", None)
else: os.environ["TORCHDYNAMO_DISABLE"] = "1"

from dftorch import Constants, Structure, ESDriver

dftorch_params = {
    "FILENAME": "COORD.pdb",
    "SKFPATH": "sk_orig/mio-1-1/mio-1-1/",  # Path to SKF files
    "T_ELECTRONIC": 1000.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 7.0,  # Electronic cutoff in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Repulsive cutoff in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "COUL_METHOD": "PME",  # 'FULL' for full coulomb matrix, 'PME' for Particle Mesh Ewald method
}

device = "cuda" if torch.cuda.is_available() else "cpu" # Use GPU if available, otherwise CPU
const = Constants(dftorch_params).to(device) # Constants container with parameters
structure1 = Structure(dftorch_params, const, device=device) # Initialize structure from input file (COORD.pdb)
es_driver = ESDriver(dftorch_params, device=device) # Initialize electronic structure driver
es_driver(structure1, const) # Compute electronic structure and forces, with SCF convergence
print(f"  {'E_total':22s} {structure1.e_tot:12.6f} Ev")

DFTB3: False
### Do _scf ###
  Initial dm_fermi
  Initial mu = 0.1376

Starting cycle
Iter 1
Res = 0.174475476, dEc = 0.051889745, t = 0.0 s

Iter 2
Res = 0.133161152, dEc = 0.763540036, t = 0.0 s

Iter 3
Res = 0.012269946, dEc = 0.998083401, t = 0.0 s

Iter 4
Res = 0.000378782, dEc = 0.043601636, t = 0.0 s

Iter 5
Res = 0.000202957, dEc = 0.003322382, t = 0.0 s

Iter 6
Res = 0.000039972, dEc = 0.001255965, t = 0.0 s

Iter 7
Res = 0.000001828, dEc = 0.000143381, t = 0.0 s

Iter 8
Res = 0.000001095, dEc = 0.000001316, t = 0.0 s

Iter 9
Res = 0.000000177, dEc = 0.000004494, t = 0.0 s

  E_total                  -76.380197 Ev


# 0. NVIDIA Alchemi for neighbor list construction
### Uncomment code below to use NVIDIA Alchemi for neighbor list construction.
#### In this tutorial, we use the vectorized brute-force $N^2$ algorithm because the example systems are small and it avoids extra GPU/backend-specific setup that can vary across environments.

In [29]:
# import dftorch._nearestneighborlist as _nnl
# _nnl.USE_ALCHEMI = True   # all subsequent calls use alchemi by default

# 1. MD with PBC and PME
### Note, cell dimensions must be >= (2 x COULOMB_CUTOFF) if using PME.

## First, SCF and forces

In [30]:
%%time
dftorch_params = {
    ### mandatory: ###
    "FILENAME": "COORD.pdb",
    "SKFPATH": "sk_orig/mio-1-1/mio-1-1/",  # Path to SKF files
    "T_ELECTRONIC": 1000.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "COUL_METHOD": "PME",  # 'FULL' for full coulomb matrix, 'PME' for Particle Mesh Ewald method

    ### optional: ###
    #"CELL": [[25.0, 0.0, 0.0], [0.0, 25.0, 0.0], [0.0, 0.0, 25.0]], # or simply [A,B,C] for orthorombic cell. Simulation box vectors in Angstroms. Overrides cell information in .pdb or wraps .xyz.

    # "SCF_ALPHA": 0.1,  # Scaled delta function coefficient. Acts as linear mixing coefficient used before Krylov acceleration starts.
    # "SCF_MAX_ITER": 100,  # Maximum number of SCF iterations. Default is 100.
    # "SCF_TOL": 1e-6,  # SCF convergence tolerance on density matrix
    
    # "COULOMB_CUTOFF": 10.0,  # Coulomb cutoff
    # "COULOMB_ACC": 1e-5,  # Coulomb accuracy for full coulomb calcs or t_err for PME
    # "PME_ORDER": 4,  # Ignored for FULL coulomb method

    # "KRYLOV_START": 10,  # Number of initial SCF iterations before starting Krylov acceleration
    # "KRYLOV_MAXRANK": 20,  # Maximum Krylov subspace rank
    # "KRYLOV_TOL": 1e-6,  # Krylov subspace convergence tolerance in SCF
    # "KRYLOV_TOL_MD": 1e-2,  # Krylov subspace convergence tolerance in MD SCF

    # "CHARGE": 0,  # Total charge of the system. Default is 0 (neutral).
    # "UNRESTRICTED": False, # Whether to perform unrestricted (spin-polarized) calculation. Default is False (restricted).
    # "SPIN_POL": 0,  # Spin polarization (N_alpha - N_beta). Default is 0 (non-magnetic).
    # "SHARED_MU": False, # Whether to use shared chemical potential for alpha and beta spin channels. Default is False (per-channel chemical potentials).
    # "BROKEN_SYM": False, # if True, mix 10 % of lumo in homo at initialization.
    # "MAGNETIC_HUBBARD_LDEP": False,  # Whether to use magnetic Hubbard LDEP. Default is False.

    # "ELECTRIC_FIELD": [0.0, 0.0, 0.0],  # External electric field in V/Angstrom. Default is None

    # "D3_PARAMS": {"s6": 1.0, "s8": 0.5883, "a1": 0.5719, "a2": 3.6107}, # D3 dispersion parameters
    
    # "SOLVENT_PARAM_FILE": "sk_orig/mio-1-1/mio-1-1/solvation/param_gbsa1_h2o.txt",
    # "SOLVATION_MODEL": "gbsa", # gbsa (default) or alpb
    # "GBSA_DIFFERENTIABLE": True,  # Whether to use differentiable GBSA. Default is False.

    # "H_DAMP_EXP": 4.0,  # Exponential damping factor for hydrogen bonds. Default is None.
    # "H5_PARAMS": {
    #     "r_scaling": 0.714,
    #     "w_scaling": 0.25,
    #     "h5_scaling": {8: 0.06, 7: 0.18, 16: 0.21},  # O, N, S
    # }, # H5 correction. Default is None. Mutually exclusive with H_DAMP_EXP.
    # 'ANDERSON_DEPTH': 0 # Anderson extrapolation depth for MD SCF. Default is 8. Set to 0 to disable Anderson extrapolation and use simple linear mixing in MD SCF.

    # "GRAD_PARAM": False,  # Whether to use parameter gradients. Default is False.
    # "GRAD_XYZ": False,  # Whether to use gradients with respect to atomic coordinates. Default is False.
    # "GRAD_CELL": False,  # Whether to use gradients with respect to cell parameters. Default is False.
}

device = "cuda" if torch.cuda.is_available() else "cpu"

# Constants container.
const = Constants(dftorch_params).to(device)

# Structure object.
structure1 = Structure(dftorch_params, const, device=device)

# Electronic structuredriver and SCF calculation
es_driver = ESDriver(dftorch_params, device=device)
es_driver(structure1, const, do_scf=True)
es_driver.calc_forces(structure1, const)  # Calculate forces after SCF
es_driver.calc_stress(structure1, const)  # Calculate stress after SCF

DFTB3: False
### Do _scf ###
  Initial dm_fermi
  Initial mu = 0.1376

Starting cycle
Iter 1
Res = 0.174475635, dEc = 0.051889868, t = 0.0 s

Iter 2
Res = 0.133161271, dEc = 0.763540641, t = 0.0 s

Iter 3
Res = 0.012269939, dEc = 0.998084350, t = 0.0 s

Iter 4
Res = 0.000378782, dEc = 0.043601552, t = 0.0 s

Iter 5
Res = 0.000202957, dEc = 0.003322382, t = 0.0 s

Iter 6
Res = 0.000039972, dEc = 0.001255965, t = 0.0 s

Iter 7
Res = 0.000001828, dEc = 0.000143381, t = 0.0 s

Iter 8
Res = 0.000001095, dEc = 0.000001316, t = 0.0 s

Iter 9
Res = 0.000000177, dEc = 0.000004494, t = 0.0 s

CPU times: user 5.54 s, sys: 8.35 ms, total: 5.54 s
Wall time: 1.04 s


In [32]:
Ha = 0.0367493  # correct eV → Ha conversion
# print(f"  {'net spin':22s} {structure1.net_spin_sr.sum().item():12.4f}")
print(
    f"  {'E_total':22s} {structure1.e_tot * Ha:12.6f} Ha  ({structure1.e_tot:12.6f} Ev)"
)
print(f"{'Energy Components':─^52}")
print(
    f"  {'E_band':22s} {structure1.e_band0 * Ha:12.6f} Ha  ({structure1.e_band0:12.6f} Ev)"
)
print(
    f"  {'E_coulomb':22s} {structure1.e_coul * Ha:12.6f} Ha  ({structure1.e_coul:12.6f} Ev)"
)
print(
    f"  {'E_repulsion':22s} {structure1.e_repulsion * Ha:12.6f} Ha  ({structure1.e_repulsion:12.6f} Ev)"
)
print(
    f"  {'E_entropy (-TS)':22s} {structure1.e_entropy * Ha:12.6f} Ha  ({structure1.e_entropy:12.6f} Ev)"
)
print(f"{'─' * 52}")
print(
    f"  {'Chemical Potential':22s} {structure1.mu0 * Ha:12.6f} Ha  ({structure1.mu0:12.6f} Ev)"
)

  E_total                   -2.806919 Ha  (  -76.380196 Ev)
─────────────────Energy Components──────────────────
  E_band                    -2.805171 Ha  (  -76.332634 Ev)
  E_coulomb                  0.008244 Ha  (    0.224336 Ev)
  E_repulsion               -0.009992 Ha  (   -0.271899 Ev)
  E_entropy (-TS)            0.000000 Ha  (    0.000000 Ev)
────────────────────────────────────────────────────
  Chemical Potential         0.013617 Ha  (    0.370528 Ev)


In [33]:
# total forces
structure1.f_tot

tensor([[-7.1295, -0.4441, -5.7436, -2.7176, -1.3527,  0.7376,  0.9534, -5.2332,
         -2.0081,  5.6942,  0.4399,  1.0332, -5.3108, -1.9432,  5.6100,  9.7663,
          1.7178, -0.8578,  0.7372,  6.0508],
        [ 0.1583, -0.1344, -0.5543, -0.6012,  0.8910,  0.6657, -0.2389, -0.4366,
         -1.2109,  1.1684,  0.7088, -0.2848, -0.5645, -1.0845,  1.2458,  0.3949,
          0.0244, -0.8537, -0.5532,  1.2597],
        [-2.1671, -0.1633, -0.6443, -0.7837,  0.7388,  0.2193, -0.0745, -1.0433,
         -0.8361,  1.6963,  0.1460, -0.1326, -0.9217, -0.8679,  1.8098,  1.0941,
          0.1167,  0.3573, -0.1671,  1.6232]], device='cuda:0')

In [34]:
# total stresses
structure1.stress_tot

tensor([[-0.0046,  0.0003, -0.0007],
        [ 0.0003, -0.0006, -0.0001],
        [-0.0007, -0.0001, -0.0007]], device='cuda:0')

In [35]:
# charges:
structure1.q

tensor([ 0.3665, -0.0730, -0.1295, -0.0957, -0.0732,  0.4510, -0.0757, -0.1167,
        -0.0820, -0.1785,  0.4478, -0.0759, -0.1190, -0.0816, -0.1759,  0.3883,
        -0.0822, -0.0522, -0.0563, -0.1862], device='cuda:0')

In [36]:
# MO coeffs
structure1.Q

tensor([[ 0.2982, -0.4212,  0.4327,  ..., -0.2193,  0.2001, -0.1120],
        [ 0.0685, -0.0474, -0.0530,  ..., -0.0035,  0.0572, -0.0572],
        [-0.0006,  0.0009, -0.0034,  ..., -0.0145,  0.0670, -0.0569],
        ...,
        [ 0.0609,  0.1394,  0.1947,  ...,  0.1113,  0.0835,  0.0371],
        [ 0.0673,  0.1524,  0.2086,  ...,  0.2073,  0.1586,  0.0778],
        [ 0.1522,  0.2505,  0.1776,  ...,  0.3381,  0.4120,  0.2965]],
       device='cuda:0')

## MD

In [37]:
torch.manual_seed(0)
temperature_K = torch.tensor(1.0, device=structure1.device)
mdDriver = MDXL(es_driver, const, temperature_K=temperature_K)

mdDriver.enable_langevin(gamma=0.02)  # thermostat. also needed for proper NPT
mdDriver.enable_barostat(  # barostat
    target_pressure=0.0,  # GPa
    tau=200.0,  # fs
    isotropic=True,
    compressibility=4.57e-5,  # 1/bar (water at 300 K)
)

# Set number of steps, time step (fs), dump interval and trajectory filename
mdDriver.run(
    structure1,
    dftorch_params,
    num_steps=5,
    dt=0.3,
    dump_interval=1,
    traj_filename="md_trj",
)

########## Step = 0 ##########
H0: 0.109 s
H1: 0.017 s
  rank: 0, Fel = 0.000048
KER: 0.014 s
F AND E: 0.181 s
ETOT = -76.37786970, EPOT = -76.49131606, EKIN = 0.00232668, T = 0.89999886, ResErr = 0.000000, P = 0.3176 GPa, V = 15626.13 ų, t = 0.3 s
0.03816704 GB


########## Step = 1 ##########
H0: 0.090 s
H1: 0.014 s
  rank: 0, Fel = 0.000073
KER: 0.009 s
F AND E: 0.151 s
ETOT = -76.37908069, EPOT = -76.80541080, EKIN = 0.11223538, T = 43.41453010, ResErr = 0.001167, P = 0.3205 GPa, V = 15627.28 ų, t = 0.3 s
0.038169088 GB


########## Step = 2 ##########
H0: 0.090 s
H1: 0.014 s
  rank: 0, Fel = 0.000017
KER: 0.009 s
F AND E: 0.152 s
ETOT = -76.38724460, EPOT = -77.28758493, EKIN = 0.41816620, T = 161.75371577, ResErr = 0.002374, P = 0.3247 GPa, V = 15628.44 ų, t = 0.3 s
0.038170112 GB


########## Step = 3 ##########
H0: 0.090 s
H1: 0.015 s
  rank: 0, Fel = 0.000011
KER: 0.009 s
F AND E: 0.153 s
ETOT = -76.40019931, EPOT = -77.89201820, EKIN = 0.88738563, T = 343.25567847, ResErr 

# 2. Batched MD with PBC and full Coulomb calculations.
### Systems in a batch should have same number of atoms and orbitals. Number of electrons and atom order can be arbitrary.
### Note, Batched mode does not support PME, only full Coulomb. Also no batched open-shell.

In [38]:
%%time
dftorch_params = {
    "FILENAME": ["COORD_8WATER.xyz"] * 4,
    "CELL": torch.tensor( [[21, 21, 21], [22, 22, 22], [21, 21, 22], [22, 22, 21]], device=device),  # Simulation box vectors in Angstroms
    "SKFPATH": "sk_orig/mio-1-1/mio-1-1/",  # Path to SKF files
    "T_ELECTRONIC": 1000.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.

    "COUL_METHOD": "FULL",
}

device = "cuda"

const = Constants(dftorch_params).to(device)

structure = StructureBatch(dftorch_params, const, device=device)

es_driver = ESDriverBatch(dftorch_params, device=device)
es_driver(structure, const, do_scf=True, verbose=False)
es_driver.calc_forces(structure, const)

DFTB3: False
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
  Initial mu tensor([-1.5453, -1.5453, -1.5453, -1.5453], device='cuda:0')

Starting cycle
Iter 1
Batch 0: Res = 7.373e-01, dEc = 5.513e+00
Batch 1: Res = 7.374e-01, dEc = 5.514e+00
Batch 2: Res = 7.373e-01, dEc = 5.513e+00
Batch 3: Res = 7.373e-01, dEc = 5.513e+00
Iter 2
Batch 0: Res = 5.458e-01, dEc = 1.705e+00
Batch 1: Res = 5.459e-01, dEc = 1.705e+00
Batch 2: Res = 5.459e-01, dEc = 1.705e+00
Batch 3: Res = 5.459e-01, dEc = 1.705e+00
Iter 3
Batch 0: Res = 1.461e-02, dEc = 1.590e-02
Batch 1: Res = 1.460e-02, dEc = 1.590e-02
Batch 2: Res = 1.460e-02, dEc = 1.590e-02
Batch 3: Res = 1.461e-02, dEc = 1.590e-02
Iter 4
Batch 0: Res = 2.943e-03, dEc = 1.823e-02
Batch 1: Res = 2.943e-03, dEc = 1.823e-02
Batch 2: Res = 2.943e-03, dEc = 1.823e-02
Batch 3: Res = 2.943e-03, dEc = 1.823e-02
Iter 5
Batch 0: Res = 4.307e-03, dEc = 1.125e-02
Batch 1: Res = 4.306e-03, dEc = 1.124e-02
Batch 2: Res = 4.306e-03, dEc = 1.125e-02
Batch 3: Res = 4

In [39]:
torch.manual_seed(0)
temperature_K = torch.tensor([20.0, 30.0, 30.0, 30.0], device=structure.device)
mdDriver = MDXLBatch(es_driver, const, temperature_K=temperature_K)
mdDriver.enable_langevin(gamma=0.02)  # thermostat
mdDriver.run(
    structure,
    dftorch_params,
    num_steps=5,
    dt=0.3,
    dump_interval=1,
    traj_filename="batch_md/md_trj",
)

########## Step = 0 ##########
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
H0: 1.309 s
H1: 0.008 s
  rank: 0, batch 0, Fel = 0.000013
  rank: 0, batch 1, Fel = 0.000014
  rank: 0, batch 2, Fel = 0.000012
  rank: 0, batch 3, Fel = 0.000013
  Not converged: 0
KER: 0.003 s
F AND E: 0.002 s
ETOT = -110.60058054, EPOT = -886.48165114, EKIN = 0.05687440, T = 18.33331009, ResErr = 0.000000, t = 1.4 s
ETOT = -110.57159404, EPOT = -886.46293555, EKIN = 0.08531159, T = 27.49996514, ResErr = 0.000000, t = 1.4 s
ETOT = -110.57182773, EPOT = -886.44544501, EKIN = 0.08531159, T = 27.49996514, ResErr = 0.000000, t = 1.4 s
ETOT = -110.57190710, EPOT = -886.45803150, EKIN = 0.08531159, T = 27.49996514, ResErr = 0.000000, t = 1.4 s
0.036192256 GB


########## Step = 1 ##########
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
H0: 1.275 s
H1: 0.008 s
  rank: 0, batch 0, Fel = 0.000020
  rank: 0, batch 1, Fel = 0.000020
  rank: 0, batch 2, Fel = 0.000021
  rank: 0, batch 3, Fel = 0.000022
  Not converge

# 3. Open-Shell MD.
### Turn on PBC if necessary. No batch mode for open-shell
## First, SCF and forces

In [40]:
%%time
dftorch_params = {
    "FILENAME": "O2.xyz",
    "SKFPATH": "sk_orig/mio-1-1/mio-1-1/",  # Path to SKF files
    "T_ELECTRONIC": 500.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.

    "UNRESTRICTED": True,
    "SPIN_POL": 2,  # Spin polarization (N_alpha - N_beta). Default is 0 (non-magnetic).
    "COUL_METHOD": "!PME",  # 'FULL' for full coulomb matrix, 'PME' for PME method
}

# Initial data, load atoms and coordinates, etc in COORD.dat
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create constants container. Set path to SKF files.
const = Constants(dftorch_params).to(device)

structure1 = Structure(dftorch_params, const,device=device)

es_driver = ESDriver(
    dftorch_params, device=device
)
es_driver(structure1, const, do_scf=True)
es_driver.calc_forces(structure1, const)  # Calculate forces after SCF

DFTB3: False
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
### Do _scf ###
  Initial dm_fermi

Starting cycle
Iter 1
Res = 0.000000000, dEc = 0.000000000, t = 0.0 s

CPU times: user 1.3 s, sys: 0 ns, total: 1.3 s
Wall time: 188 ms


In [43]:
Ha = 0.0367493  # correct eV → Ha conversion
print(
    f"  {'E_total':22s} {structure1.e_tot * Ha:12.6f} Ha  ({structure1.e_tot:12.6f} Ev)"
)
print(f"{'Energy Components':─^52}")
print(
    f"  {'E_band':22s} {structure1.e_band0 * Ha:12.6f} Ha  ({structure1.e_band0:12.6f} Ev)"
)
print(
    f"  {'E_coulomb':22s} {structure1.e_coul * Ha:12.6f} Ha  ({structure1.e_coul:12.6f} Ev)"
)
print(
    f"  {'E_repulsion':22s} {structure1.e_repulsion * Ha:12.6f} Ha  ({structure1.e_repulsion:12.6f} Ev)"
)
print(
    f"  {'E_entropy (-TS)':22s} {structure1.e_entropy * Ha:12.6f} Ha  ({structure1.e_entropy:12.6f} Ev)"
)
print(
    f"  {'E_spin':22s} {structure1.e_spin.item() * Ha:12.6f} Ha  ({structure1.e_spin.item():12.6f} eV)"
)
print(f"{'─' * 52}")
print(f"  {'Chemical Potential (Spin-Resolved)':22s} {structure1.mu0 * Ha} Ha  ({structure1.mu0} Ev)")
print(f"  {'net spin':22s} {structure1.net_spin_sr.sum().item():12.4f}")


  E_total                   -0.331896 Ha  (   -9.031347 Ev)
─────────────────Energy Components──────────────────
  E_band                    -0.462179 Ha  (  -12.576546 Ev)
  E_coulomb                  0.000000 Ha  (    0.000000 Ev)
  E_repulsion                0.158084 Ha  (    4.301676 Ev)
  E_entropy (-TS)            0.000000 Ha  (    0.000000 Ev)
  E_spin                    -0.027800 Ha  (   -0.756477 eV)
────────────────────────────────────────────────────
  Chemical Potential (Spin-Resolved) tensor([ 0.2212, -0.2875], device='cuda:0') Ha  (tensor([ 6.0182, -7.8239], device='cuda:0') Ev)
  net spin                     2.0000


In [44]:
structure1.q_tot_atom

tensor([-7.2164e-15, -7.7161e-15], device='cuda:0')

In [45]:
# net spin shell-resolved
structure1.net_spin_sr

tensor([5.5511e-16, 1.0000e+00, 1.2212e-15, 1.0000e+00], device='cuda:0')

## MD

In [46]:
torch.manual_seed(0)
temperature_K = torch.tensor(300.0, device=structure1.device)
mdDriver = MDXL(es_driver, const, temperature_K=temperature_K)
# mdDriver.NoRank = True
# Set number of steps, time step (fs), dump interval and trajectory filename
mdDriver.run(
    structure1,
    dftorch_params,
    num_steps=5,
    dt=0.2,
    dump_interval=5,
    traj_filename="md_trj.xyz",
)

########## Step = 0 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.128 s
H1: 0.003 s
  rank: 0, Fel = 0.000000
KER: 0.005 s
F AND E: 0.004 s
ETOT = -8.99256860, EPOT = -9.02871676, EKIN = 0.03877800, T = 149.99980985,  NS = 2.0000, ResErr = 0.000000, t = 0.1 s
0.033296896 GB


########## Step = 1 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.095 s
H1: 0.003 s
  rank: 0, Fel = 0.000000
KER: 0.005 s
F AND E: 0.004 s
ETOT = -8.99256612, EPOT = -9.02587471, EKIN = 0.03615064, T = 139.83674355,  NS = 2.0000, ResErr = 0.001184, t = 0.1 s
0.033296384 GB


########## Step = 2 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.093 s
H1: 0.003 s
  rank: 0, Fel = 0.000000
KER: 0.005 s
F AND E: 0.004 s
ETOT = -8.99256332, EPOT = -9.02286628, EKIN = 0.03331139, T = 128.85403942,  NS = 2.0000, ResErr = 0.000171, t = 0.1 s
0.033296896 GB


########## Step = 3 ##########
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
H0: 0.098 s
H1: 0.003 s
  ran

# 4. DFTB3.
### Full (off-diagonal) and diagonal-only third corrections order are available.

In [47]:
%%time
dftorch_params = {
    "FILENAME": "O2.xyz",
    "SKFPATH": "sk_orig/3ob-3-1/",  # Path to SKF files
    "T_ELECTRONIC": 500.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.

    "UNRESTRICTED": True,
    "SPIN_POL": 2,  # Spin polarization (N_alpha - N_beta). Default is 0 (non-magnetic).

    "COUL_METHOD": "!PME",  # 'FULL' for full coulomb matrix, 'PME' for PME method

    "DFTB3": True,  # Set to True to enable DFTB3 corrections. Default is False (DFTB2).
    # "dftb3_diagonal_only": True,  # If True, use diagonal-only third-order corrections. Otherwise, use full (off-diagonal) third-order corrections. Default is False (full corrections).
}

device = "cuda" if torch.cuda.is_available() else "cpu"

const = Constants(dftorch_params).to(device)

structure1 = Structure(dftorch_params, const, device=device)

es_driver = ESDriver(dftorch_params, device=device)
es_driver(structure1, const, do_scf=True)
es_driver.calc_forces(structure1, const)  # Calculate forces after SCF

DFTB3: True
coulomb_matrix_vectorized
  Coulomb_Real t 0.0 s
### Do _scf ###
  Initial dm_fermi

Starting cycle
Iter 1
Res = 0.000000000, dEc = 0.000000000, t = 0.0 s

CPU times: user 1.85 s, sys: 3.64 ms, total: 1.85 s
Wall time: 322 ms


In [50]:
Ha = 0.0367493  # correct eV → Ha conversion
print(
    f"  {'E_total':22s} {structure1.e_tot * Ha:12.6f} Ha  ({structure1.e_tot:12.6f} Ev)"
)
print(f"{'Energy Components':─^52}")

print(
    f"  {'E_band':22s} {structure1.e_band0 * Ha:12.6f} Ha  ({structure1.e_band0:12.6f} Ev)"
)
print(
    f"  {'E_coulomb':22s} {structure1.e_coul * Ha:12.6f} Ha  ({structure1.e_coul:12.6f} Ev)"
)
print(
    f"  {'E_repulsion':22s} {structure1.e_repulsion * Ha:12.6f} Ha  ({structure1.e_repulsion:12.6f} Ev)"
)
print(
    f"  {'E_entropy (-TS)':22s} {structure1.e_entropy * Ha:12.6f} Ha  ({structure1.e_entropy:12.6f} Ev)"
)
print(
    f"  {'E_spin':22s} {structure1.e_spin.item() * Ha:12.6f} Ha  ({structure1.e_spin.item():12.6f} eV)"
)
print(f"{'─' * 52}")
print(f"  {'net spin':22s} {structure1.net_spin_sr.sum().item():12.4f}")
print(f"  {'Chemical Potential (Spin-Resolved)':22s} {structure1.mu0 * Ha} Ha  ({structure1.mu0} Ev)")

  E_total                   -0.303920 Ha  (   -8.270081 Ev)
─────────────────Energy Components──────────────────
  E_band                    -0.406516 Ha  (  -11.061881 Ev)
  E_coulomb                  0.000000 Ha  (    0.000000 Ev)
  E_repulsion                0.130447 Ha  (    3.549637 Ev)
  E_entropy (-TS)            0.000000 Ha  (    0.000000 Ev)
  E_spin                    -0.027850 Ha  (   -0.757837 eV)
────────────────────────────────────────────────────
  net spin                     2.0000
  Chemical Potential (Spin-Resolved) tensor([ 0.2020, -0.2871], device='cuda:0') Ha  (tensor([ 5.4976, -7.8110], device='cuda:0') Ev)


In [51]:
structure1.q_tot_atom

tensor([-5.4956e-15, -6.3283e-15], device='cuda:0')

In [52]:
# net spin shell-resolved
structure1.net_spin_sr

tensor([9.9920e-16, 1.0000e+00, 3.3307e-16, 1.0000e+00], device='cuda:0')

# 5. Backprop.
## Backprop is only supported for full coulomb summation (no PME).
### 1. Through coordinates.

In [53]:
dftorch_params = {
    "FILENAME": ["COORD_8WATER.xyz"] * 4,
    "CELL": torch.tensor( [[21, 21, 21], [22, 22, 22], [21, 21, 22], [22, 22, 21]], device=device),  # Simulation box vectors in Angstroms
    "SKFPATH": "sk_orig/mio-1-1/mio-1-1/",  # Path to SKF files
    "T_ELECTRONIC": 1000.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.

    "COUL_METHOD": "FULL",

    "GRAD_XYZ": True,
}

device = "cuda"

const = Constants(dftorch_params).to(device)

structure = StructureBatch(
    dftorch_params,
    const,
    device=device,
)

es_driver = ESDriverBatch(
    dftorch_params, device=device
)
es_driver(structure, const, do_scf=True, verbose=False)
es_driver.calc_forces(structure, const)

DFTB3: False
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
  Initial mu tensor([-1.5453, -1.5453, -1.5453, -1.5453], device='cuda:0',
       grad_fn=<MulBackward0>)

Starting cycle
Iter 1
Batch 0: Res = 7.373e-01, dEc = 5.513e+00
Batch 1: Res = 7.374e-01, dEc = 5.514e+00
Batch 2: Res = 7.373e-01, dEc = 5.513e+00
Batch 3: Res = 7.373e-01, dEc = 5.513e+00
Iter 2
Batch 0: Res = 5.458e-01, dEc = 1.705e+00
Batch 1: Res = 5.459e-01, dEc = 1.705e+00
Batch 2: Res = 5.459e-01, dEc = 1.705e+00
Batch 3: Res = 5.459e-01, dEc = 1.705e+00
Iter 3
Batch 0: Res = 1.461e-02, dEc = 1.590e-02
Batch 1: Res = 1.460e-02, dEc = 1.590e-02
Batch 2: Res = 1.460e-02, dEc = 1.590e-02
Batch 3: Res = 1.461e-02, dEc = 1.590e-02
Iter 4
Batch 0: Res = 2.943e-03, dEc = 1.823e-02
Batch 1: Res = 2.943e-03, dEc = 1.823e-02
Batch 2: Res = 2.943e-03, dEc = 1.823e-02
Batch 3: Res = 2.943e-03, dEc = 1.823e-02
Iter 5
Batch 0: Res = 4.307e-03, dEc = 1.125e-02
Batch 1: Res = 4.306e-03, dEc = 1.124e-02
Batch 2: Res = 4.306e-03, d

In [54]:
grads = torch.autograd.grad(
    structure.e_tot.sum(), [structure.RX, structure.RY, structure.RZ]
)
forces_backprop = -torch.stack(grads, dim=1)

# compare forces from backprop with analytical forces from ESDriver.
(structure.f_tot - forces_backprop).abs().max()

tensor(3.9122e-08, device='cuda:0', grad_fn=<MaxBackward1>)

### 2. Through DFTB parameters (on-site orbital energies).

In [55]:
dftorch_params = {
    "FILENAME": ["COORD_8WATER.xyz"] * 4,
    "CELL": torch.tensor( [[21, 21, 21], [22, 22, 22], [21, 21, 22], [22, 22, 21]], device=device),  # Simulation box vectors in Angstroms
    "SKFPATH": "sk_orig/mio-1-1/mio-1-1/",  # Path to SKF files
    "T_ELECTRONIC": 1000.0,  # Electronic temperature in Kelvin for Fermi smearing
    "RCUT_ELECTRONIC": 8.0,  # Cutoff for electronic interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.
    "RCUT_REPULSIVE": 4.0,  # Cutoff for repulsive interactions in Angstroms. Should be >= largest cutoff in SKF files for the element pairs present in the system.

    "COUL_METHOD": "FULL",
    
    "GRAD_PARAM": True,
}
# Initial data, load atoms and coordinates, etc in COORD.dat
device = "cuda"

const = Constants(
    dftorch_params
).to(device)

structure = StructureBatch(
    dftorch_params,
    const,
    device=device,
)

es_driver = ESDriverBatch(
    dftorch_params, device=device
)
es_driver(structure, const, do_scf=True, verbose=False)
es_driver.calc_forces(structure, const)

DFTB3: False
   LMAX: tensor([8, 9, 8, 9], device='cuda:0')
  Initial mu tensor([-1.5453, -1.5453, -1.5453, -1.5453], device='cuda:0',
       grad_fn=<MulBackward0>)

Starting cycle
Iter 1
Batch 0: Res = 7.373e-01, dEc = 5.513e+00
Batch 1: Res = 7.374e-01, dEc = 5.514e+00
Batch 2: Res = 7.373e-01, dEc = 5.513e+00
Batch 3: Res = 7.373e-01, dEc = 5.513e+00
Iter 2
Batch 0: Res = 5.458e-01, dEc = 1.705e+00
Batch 1: Res = 5.459e-01, dEc = 1.705e+00
Batch 2: Res = 5.459e-01, dEc = 1.705e+00
Batch 3: Res = 5.459e-01, dEc = 1.705e+00
Iter 3
Batch 0: Res = 1.461e-02, dEc = 1.590e-02
Batch 1: Res = 1.460e-02, dEc = 1.590e-02
Batch 2: Res = 1.460e-02, dEc = 1.590e-02
Batch 3: Res = 1.461e-02, dEc = 1.590e-02
Iter 4
Batch 0: Res = 2.943e-03, dEc = 1.823e-02
Batch 1: Res = 2.943e-03, dEc = 1.823e-02
Batch 2: Res = 2.943e-03, dEc = 1.823e-02
Batch 3: Res = 2.943e-03, dEc = 1.823e-02
Iter 5
Batch 0: Res = 4.307e-03, dEc = 1.125e-02
Batch 1: Res = 4.306e-03, dEc = 1.124e-02
Batch 2: Res = 4.306e-03, d

In [56]:
grads = torch.autograd.grad(structure.e_tot.sum(), [const.Es, const.Ep])
grads = torch.stack(grads, dim=0)

In [57]:
print("dE/dEs_H:", grads[0, 1].item())
print("dE/dEs_O:", grads[0, 8].item())
print("dE/dEp_O:", grads[1, 8].item())

dE/dEs_H: -36.14599437362467
dE/dEs_O: -11.854215717157498
dE/dEp_O: 11.815163945217948
